function [filelist]=output_runfiles_hex_v9_isovisc(outstm,vox,muest,rhoest,DR,inpath,nodhmgf,elmhmgf,bcoutf,regoutf,freqHz,dspoutf,outpath,znedgelength,znovlp,noreg,noDTI)
%output_runfiles_hex outputs runfiles and submit files for a hexahedral
%mesh
%   Detailed explanation goes here
vincomp=0.499; % Default Incompressible Poisson Ratio
vcomp=0.4; % Default compressible Poisson ratio
Ndisp=length(freqHz);

%% Hexahedral isotropic visocelastic runfiles
ifile=0;

    %% MREv9 runfile
    % Hexahedral Iso incompressible run file - viscoelastic - Soft Prior On
    if(~noreg) % do not output soft prior runfiles without a supplied segmentation.
        
        viscoutputfv9isoincomp=[outstm  '_G' sprintf('%0.0f',muest) '.v9.hex.inv.iso.incomp.visc_SPon'];
        viscrfilev9_SP='runfile-v9visc.dat_SP1en9';
        ifile=ifile+1;
        filelist(ifile).runf=viscrfilev9_SP;
        filelist(ifile).outf=viscoutputfv9isoincomp;
        filelist(ifile).decription='MRE v9, soft prior on, isotropic VE incompressible';
        
        fid=fopen([inpath viscrfilev9_SP],'w');
        fprintf(fid,'Subzone Reconstruction Data File \n');
        fprintf(fid,'Problem Type <0=Forward Problem Only> <1+=Inverse Problem> \n');
        fprintf(fid,'1 \n');
        fprintf(fid,'Node File: \n');
        fprintf(fid,'%c',nodhmgf);fprintf(fid,'\n');
        fprintf(fid,'Element File: \n');
        fprintf(fid,'%c',elmhmgf);fprintf(fid,'\n');
        fprintf(fid,'Boundary Node File: \n');
        fprintf(fid,'%c',bcoutf);fprintf(fid,'\n');
        fprintf(fid,'Pressure BC file: \n');
        fprintf(fid,'UNUSED');fprintf(fid,'\n');
        fprintf(fid,'Region Stack File: \n');
        fprintf(fid,'%c',regoutf);fprintf(fid,'\n');
        fprintf(fid,'Measured Displacement File: \n');
        fprintf(fid,'%i',Ndisp);fprintf(fid,'\n');
        for idisp=1:Ndisp
            fprintf(fid,'%10.4fd0',freqHz(idisp));fprintf(fid,'\n');
            fprintf(fid,'%c',dspoutf{idisp});fprintf(fid,'\n');
        end
        fprintf(fid,'Initial Solution File: \n');
        fprintf(fid,'0 \n');
        fprintf(fid,'Output File Stem: \n');
        fprintf(fid,'%c',outpath);fprintf(fid,'%c',viscoutputfv9isoincomp);fprintf(fid,'\n');
        fprintf(fid,'Print Detailed Runtime Debugging and Execution Comments <verb> <file>:\n');
        fprintf(fid,'.false.,.false. \n');
        fprintf(fid,'Material Model <1=isotropic> <2=orthotropic> <3=iso compress> <4=poro>: \n');
        fprintf(fid,'1 \n');
        fprintf(fid,'Number of Material Properties: \n');
        fprintf(fid,'3 \n');
        fprintf(fid,'Material Description Style <1=nodal> <2=element> [<shear modulus> <density> <bulk modulus>]: \n');
        fprintf(fid,'1,1,1 \n');
        fprintf(fid,'Number of Parameters per Material Point: \n');
        fprintf(fid,'1,1,1 \n');
        fprintf(fid,'Property Scalars: \n');
        fprintf(fid,'%5.0f.d0,%5.0f.d0,%5.0f.d0,%8.5fd0,%10.0f.d0,%9.5fd0',[muest 2*DR*muest rhoest -1d-1 2*muest*(1+vincomp)/(3*(1-2*vincomp)) 0.0001]);fprintf(fid,'\n');
        fprintf(fid,'Zone displacement boundary condition option: 1=measured data, 2=seperate file (needs disp files on the following lines),3=calculated displacements \n');
        fprintf(fid,'1 \n');
		fprintf(fid,'Multifrequency Indicator \n');
        fprintf(fid,'.false.,.false.,.false. \n');
        fprintf(fid,'Multifrequency Alpha \n');
        fprintf(fid,'0.d0,0.d0,0.d0 \n');
        fprintf(fid,'0.d0,0.d0,0.d0 \n');
        fprintf(fid,'Number of Material Property Mesh Resolutions: \n');
        fprintf(fid,'2 \n');
        fprintf(fid,'Number of material mesh structures \n');
        fprintf(fid,'3 \n');
        fprintf(fid,'Material mesh iteration stucture (one less than number of structures)  \n');
        fprintf(fid,'3,6 \n');
        fprintf(fid,'Material Property Mesh Resolutions (x,y,z): \n');
        fprintf(fid,'%9.7f , %9.7f , %9.7f \n',vox);
        fprintf(fid,'%9.7f , %9.7f , %9.7f \n',10.*vox);
        fprintf(fid,'Material Mesh Index (1st line real part, 2nd line imag) \n ');
        fprintf(fid,'1 2 2 \n');
        fprintf(fid,'1 2 2 \n');
        fprintf(fid,'Material Mesh Index (1st line real part, 2nd line imag) \n ');
        fprintf(fid,'1 2 2 \n');
        fprintf(fid,'1 2 2 \n');
        fprintf(fid,'Material Mesh Index (1st line real part, 2nd line imag) \n ');
        fprintf(fid,'1 2 2 \n');
        fprintf(fid,'1 2 2 \n');
        fprintf(fid,'Reconstruction Indicators: \n');
        fprintf(fid,'.true.,.true. \n');
        fprintf(fid,'.false.,.false. \n');
        fprintf(fid,'.false.,.false. \n');
        fprintf(fid,'Property Estimate Variance Calculation: \n');
        fprintf(fid,'.false. \n');
        fprintf(fid,'Global forward solve to check displacement error \n');
        fprintf(fid,'.false. \n');
        fprintf(fid,'Zone Sizes (not including overlap factor, actual size = (1+2*ovlp)*siz) [x y z]: \n');
        fprintf(fid,'%12.5e,%12.5e,%12.5e',znedgelength);fprintf(fid,'\n');
        fprintf(fid,'Zone Overlap Percentage [x y z]: \n');
        fprintf(fid,'%4.3fd0,%4.3fd0,%4.3fd0',znovlp);fprintf(fid,'\n');
        fprintf(fid,'Iteration Limits [global zone]: \n');
        fprintf(fid,'100,1 \n');
        fprintf(fid,'Minimum Parameter Update Size [global zone line]: \n');
        fprintf(fid,'%c','1.d-5, 1d-5, 1.d-5');fprintf(fid,'\n');
        fprintf(fid,'Number of Zone Iteration Structures: \n');
        fprintf(fid,'3 \n');
        fprintf(fid,'Iteration Limits for Zone Iteration Structures (NOTE:  provide one less limit than # of structures!!!): \n');
        fprintf(fid,'10,150 \n');
        fprintf(fid,'Zone Iteration Structures [<# of CG iters> <# of GN iters> <!!! QN CURRENTLY UNAVAILABLE !!!> <# of line search iters>]: \n');
        fprintf(fid,'1,0,0,1 \n');
        fprintf(fid,'2,0,0,2 \n');
        fprintf(fid,'3,0,0,2 \n');
        fprintf(fid,'Number of Processors per MUMPS Communicator \n');
        fprintf(fid,'1 \n');
        fprintf(fid,'Maximum Amount of RAM per Processor [MB] \n');
        fprintf(fid,'999999999 \n');
        fprintf(fid,'ooooooooooo  REGULARIZATION DESCRIPTORS  ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo \n');
        fprintf(fid,'Regularization Indicators [<TV> <SF> <TK> <MQ> <JW> <constraints> <CG residual> <VH> <McG> <soft prior>]: \n');
        fprintf(fid,'.false.,.true.,.false.,.false.,.false.,.false.,.true.,.true.,.true.,.true. \n');
        fprintf(fid,'Number of constant regularization iterations (final N iterations use final regularization weights) \n');
        fprintf(fid,'30 \n');
        fprintf(fid,'Number of Parameters to Treat with Total Variation: \n');
        fprintf(fid,'3 \n');
        fprintf(fid,'TV Parameter List: \n');
        fprintf(fid,'1,2,3 \n');
        fprintf(fid,'TV Delta Values: <1st line real, 2nd line imag> \n');
        fprintf(fid,'1.d-19,1.d-19,1.d-19 \n');
        fprintf(fid,'1.d-19,1.d-19,1.d-19 \n');
        fprintf(fid,'TV Initial Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'5.d-16,5.d-16,5.d-16 \n');
        fprintf(fid,'5.d-16,5.d-16,5.d-16 \n');
        fprintf(fid,'TV Final Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'5.d-16,5.d-16,5.d-16 \n');
        fprintf(fid,'5.d-16,5.d-16,5.d-16 \n');
        fprintf(fid,'Number of Parameters to Treat with Spatial Filtering: \n');
        fprintf(fid,'3 \n');
        fprintf(fid,'SF Parameter List: \n');
        fprintf(fid,'1,2,3 \n');
        fprintf(fid,'SF Gaussian filter initial Widths: <1st line real, 2nd line imag> \n');
        fprintf(fid,'0.003d0,0.003d0,0.003d0 \n');
        fprintf(fid,'0.003d0,0.003d0,0.003d0 \n');
        fprintf(fid,'SF Final Gaussian width: <1st line real, 2nd line imag> \n');
        fprintf(fid,'0.0015d0,0.0015d0,0.0015d0 \n');
        fprintf(fid,'0.0015d0,0.0015d0,0.0015d0 \n');
        fprintf(fid,'Number of Parameters to Treat with Tikhonov Regularization: \n');
        fprintf(fid,'3 \n');
        fprintf(fid,'TK Parameter List: \n');
        fprintf(fid,'1,2,3 \n');
        fprintf(fid,'TK Initial Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'1.d-18,1.d-18,1.d-18 \n');
        fprintf(fid,'1.d-18,1.d-18,1.d-18 \n');
        fprintf(fid,'TK Final Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'1.d-18,1.d-18,1.d-18 \n');
        fprintf(fid,'1.d-18,1.d-18,1.d-18 \n');
        fprintf(fid,'Number of Parameters to Treat with Marquardt Regularization: \n');
        fprintf(fid,'3 \n');
        fprintf(fid,'Distance of alpha from 1 at which MQ weights are adjusted: \n');
        fprintf(fid,'0.25d0 \n');
        fprintf(fid,'MQ Parameter List: \n');
        fprintf(fid,'1,2,3 \n');
        fprintf(fid,'MQ Weight Delta: <1st line real, 2nd line imag> \n');
        fprintf(fid,'0.5d0,0.5d0,0.5d0 \n');
        fprintf(fid,'0.5d0,0.5d0,0.5d0 \n');
        fprintf(fid,'MQ Initial Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'1.d2,1.d2,1.d2 \n');
        fprintf(fid,'1.d2,1.d2,1.d2 \n');
        fprintf(fid,'MQ Minimum Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
        fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
        fprintf(fid,'Number of Parameters to Treat with Joachimowicz Regularization: \n');
        fprintf(fid,'3 \n');
        fprintf(fid,'JW Parameter List: \n');
        fprintf(fid,'1,2,3 \n');
        fprintf(fid,'JW Initial Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'5.d0,5.d0,5.d0 \n');
        fprintf(fid,'5.d0,5.d0,5.d0 \n');
        fprintf(fid,'JW Final Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'5.d0,5.d0,5.d0 \n');
        fprintf(fid,'5.d0,5.d0,5.d0 \n');
        fprintf(fid,'Number of Parameters to Treat with Constraints: \n');
        fprintf(fid,'3 \n');
        fprintf(fid,'Constraint Parameter List: \n');
        fprintf(fid,'1,2,3 \n');
        fprintf(fid,'Constraint Weights <converges to exact solution as weight --> inf>: \n');
        fprintf(fid,'1.d-14,1.d-14,1.d-14 \n');
        fprintf(fid,'Constraint Minimums: \n');
        fprintf(fid,'200.d0, 1.d0, 1000.d0, -5.d4, 1000.d0, 0.d0 \n');
        fprintf(fid,'Constraint Maximums: \n');
        fprintf(fid,'5.d5, 5.d5, 1000.d0, -1.d-2, 1.d12, 0.d0 \n');
        fprintf(fid,'CG Residual Scaling Initial Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'0.04d0,0.04d0,0.04d0 \n');
        fprintf(fid,'0.04d0,0.04d0,0.04d0 \n');
        fprintf(fid,'CG Residual Scaling Final Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'0.01d0,0.01d0,0.01d0 \n');
        fprintf(fid,'0.01d0,0.01d0,0.01d0 \n');
        fprintf(fid,'Van Houten Regularization Level: \n');
        fprintf(fid,'1.2d0 \n');
        fprintf(fid,'Number of parameters to treat with soft prior: \n');
        fprintf(fid,'3 \n');
        fprintf(fid,'SP Parameter List: \n');
        fprintf(fid,'1,2,3 \n');
        fprintf(fid,'SP Initial Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'1.d-9,1.d-9,1.d-9 \n');
        fprintf(fid,'1.d-9,1.d-9,1.d-9 \n');
        fprintf(fid,'SP Final Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'1.d-9,1.d-9,1.d-9 \n');
        fprintf(fid,'1.d-9,1.d-9,1.d-9 \n');
        fprintf(fid,'SP start iteration delay (first N iterations do not use soft prior \n');
        fprintf(fid,'0 \n');
        fclose(fid);

    end

    %% MREv9 runfile
    % Iso incompressible run file - viscoelastic - No soft Prior
    viscoutputfv9isoincomp_noSP=[outstm  '_G' sprintf('%0.0f',muest) '.v9.hex.inv.iso.incomp.visc_SPoff_SF0p0015_CG2p2'];
    viscrfilev9_noSP='runfile-v9_visc_incomp.dat';
    
    ifile=ifile+1;
    filelist(ifile).runf=viscrfilev9_noSP;
    filelist(ifile).outf=viscoutputfv9isoincomp_noSP;
    filelist(ifile).decription='MRE v9, soft prior off, isotropic VE incompressible';
        
    
    fid=fopen([inpath viscrfilev9_noSP],'w');
    fprintf(fid,'Subzone Reconstruction Data File \n');
    fprintf(fid,'Problem Type <0=Forward Problem Only> <1+=Inverse Problem> \n');
    fprintf(fid,'1 \n');
    fprintf(fid,'Node File: \n');
    fprintf(fid,'%c',nodhmgf);fprintf(fid,'\n');
    fprintf(fid,'Element File: \n');
    fprintf(fid,'%c',elmhmgf);fprintf(fid,'\n');
    fprintf(fid,'Boundary Node File: \n');
    fprintf(fid,'%c',bcoutf);fprintf(fid,'\n');
    fprintf(fid,'Pressure BC file: \n');
    fprintf(fid,'UNUSED');fprintf(fid,'\n');
    fprintf(fid,'Region Stack File: \n');
    fprintf(fid,'%c',regoutf);fprintf(fid,'\n');
    fprintf(fid,'Measured Displacement File: \n');
    fprintf(fid,'%i',Ndisp);fprintf(fid,'\n');
    for idisp=1:Ndisp
        fprintf(fid,'%10.4fd0',freqHz(idisp));fprintf(fid,'\n');
        fprintf(fid,'%c',dspoutf{idisp});fprintf(fid,'\n');
    end
    fprintf(fid,'Initial Solution File: \n');
    fprintf(fid,'0 \n');
    fprintf(fid,'Output File Stem: \n');
    fprintf(fid,'%c',outpath);fprintf(fid,'%c',viscoutputfv9isoincomp_noSP);fprintf(fid,'\n');
    fprintf(fid,'Print Detailed Runtime Debugging and Execution Comments <verb> <file>:\n');
    fprintf(fid,'.false.,.false. \n');
    fprintf(fid,'Material Model <1=isotropic> <2=orthotropic> <3=iso compress>  <4=poro>: \n');
    fprintf(fid,'1 \n');
    fprintf(fid,'Number of Material Properties: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Material Description Style <1=nodal> <2=element> [<shear modulus> <density> <bulk modulus>]: \n');
    fprintf(fid,'1,1,1 \n');
    fprintf(fid,'Number of Parameters per Material Point: \n');
    fprintf(fid,'1,1,1 \n');
    fprintf(fid,'Property Scalars: \n');
    fprintf(fid,'%5.0f.d0,%5.0f.d0,%5.0f.d0,%8.5fd0,%10.0f.d0,%9.5fd0',[muest 2*DR*muest rhoest -1d-1 2*muest*(1+vincomp)/(3*(1-2*vincomp)) 0.0001]);fprintf(fid,'\n');
	fprintf(fid,'Zone displacement boundary condition option: 1=measured data, 2=seperate file (needs disp files on the following lines),3=calculated displacements \n');
    fprintf(fid,'1 \n');
    fprintf(fid,'Multifrequency Indicator \n');
    fprintf(fid,'.false.,.false.,.false. \n');
    fprintf(fid,'Multifrequency Alpha \n');
    fprintf(fid,'0.d0,0.d0,0.d0 \n');
    fprintf(fid,'0.d0,0.d0,0.d0 \n');
    fprintf(fid,'Number of Material Property Mesh Resolutions: \n');
    fprintf(fid,'2 \n');
    fprintf(fid,'Number of material mesh structures \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Material mesh iteration stucture (one less than number of structures)  \n');
    fprintf(fid,'3,6 \n');
    fprintf(fid,'Material Property Mesh Resolutions (x,y,z): \n');
    fprintf(fid,'%9.7f , %9.7f , %9.7f \n',vox);
    fprintf(fid,'%9.7f , %9.7f , %9.7f \n',10.*vox);
    fprintf(fid,'Material Mesh Index (1st line real part, 2nd line imag) \n ');
    fprintf(fid,'1 2 2 \n');
    fprintf(fid,'1 2 2 \n');
    fprintf(fid,'Material Mesh Index (1st line real part, 2nd line imag) \n ');
    fprintf(fid,'1 2 2 \n');
    fprintf(fid,'1 2 2 \n');
    fprintf(fid,'Material Mesh Index (1st line real part, 2nd line imag) \n ');
    fprintf(fid,'1 2 2 \n');
    fprintf(fid,'1 2 2 \n');
    fprintf(fid,'Reconstruction Indicators: \n');
    fprintf(fid,'.true.,.true. \n');
    fprintf(fid,'.false.,.false. \n');
    fprintf(fid,'.false.,.false. \n');
    fprintf(fid,'Property Estimate Variance Calculation: \n');
    fprintf(fid,'.false. \n');
    fprintf(fid,'Global forward solve to check displacement error \n');
    fprintf(fid,'.false. \n');
    fprintf(fid,'Zone Sizes (not including overlap factor, actual size = (1+2*ovlp)*siz) [x y z]: \n');
    fprintf(fid,'%12.5e,%12.5e,%12.5e',znedgelength);fprintf(fid,'\n');
    fprintf(fid,'Zone Overlap Percentage [x y z]: \n');
    fprintf(fid,'%4.3fd0,%4.3fd0,%4.3fd0',znovlp);fprintf(fid,'\n');
    fprintf(fid,'Iteration Limits [global zone]: \n');
    fprintf(fid,'100,1 \n');
    fprintf(fid,'Minimum Parameter Update Size [global zone line]: \n');
    fprintf(fid,'%c','1.d-5, 1d-5, 1.d-5');fprintf(fid,'\n');
    fprintf(fid,'Number of Zone Iteration Structures: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Iteration Limits for Zone Iteration Structures (NOTE:  provide one less limit than # of structures!!!): \n');
    fprintf(fid,'10,150 \n');
    fprintf(fid,'Zone Iteration Structures [<# of CG iters> <# of GN iters> <!!! QN CURRENTLY UNAVAILABLE !!!> <# of line search iters>]: \n');
    fprintf(fid,'1,0,0,1 \n');
    fprintf(fid,'2,0,0,2 \n');
    fprintf(fid,'3,0,0,2 \n');
    fprintf(fid,'Number of Processors per MUMPS Communicator \n');
    fprintf(fid,'1 \n');
    fprintf(fid,'Maximum Amount of RAM per Processor [MB] \n');
    fprintf(fid,'999999999 \n');
    fprintf(fid,'ooooooooooo  REGULARIZATION DESCRIPTORS  ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo \n');
    fprintf(fid,'Regularization Indicators [<TV> <SF> <TK> <MQ> <JW> <constraints> <CG residual> <VH> <McG> <soft prior>]: \n');
    fprintf(fid,'.false.,.true.,.false.,.false.,.false.,.false.,.true.,.true.,.true.,.false. \n');
    fprintf(fid,'Number of constant regularization iterations (final N iterations use final regularization weights) \n');
    fprintf(fid,'30 \n');
    fprintf(fid,'Number of Parameters to Treat with Total Variation: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'TV Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'TV Delta Values: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-19,1.d-19,1.d-19 \n');
    fprintf(fid,'1.d-19,1.d-19,1.d-19 \n');
    fprintf(fid,'TV Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'5.d-16,5.d-16,5.d-16 \n');
    fprintf(fid,'5.d-16,5.d-16,5.d-16 \n');
    fprintf(fid,'TV Final Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'5.d-16,5.d-16,5.d-16 \n');
    fprintf(fid,'5.d-16,5.d-16,5.d-16 \n');
    fprintf(fid,'Number of Parameters to Treat with Spatial Filtering: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'SF Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'SF Gaussian filter initial Widths: <1st line real, 2nd line imag> \n');
    fprintf(fid,'0.003d0,0.003d0,0.003d0 \n');
    fprintf(fid,'0.003d0,0.003d0,0.003d0 \n');
    fprintf(fid,'SF Final Gaussian width: <1st line real, 2nd line imag> \n');
    fprintf(fid,'0.0015d0,0.0015d0,0.0015d0 \n');
    fprintf(fid,'0.0015d0,0.0015d0,0.0015d0 \n');
    fprintf(fid,'Number of Parameters to Treat with Tikhonov Regularization: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'TK Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'TK Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-18,1.d-18,1.d-18 \n');
    fprintf(fid,'1.d-18,1.d-18,1.d-18 \n');
    fprintf(fid,'TK Final Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-18,1.d-18,1.d-18 \n');
    fprintf(fid,'1.d-18,1.d-18,1.d-18 \n');
    fprintf(fid,'Number of Parameters to Treat with Marquardt Regularization: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Distance of alpha from 1 at which MQ weights are adjusted: \n');
    fprintf(fid,'0.25d0 \n');
    fprintf(fid,'MQ Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'MQ Weight Delta: <1st line real, 2nd line imag> \n');
    fprintf(fid,'0.5d0,0.5d0,0.5d0 \n');
    fprintf(fid,'0.5d0,0.5d0,0.5d0 \n');
    fprintf(fid,'MQ Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d2,1.d2,1.d2 \n');
    fprintf(fid,'1.d2,1.d2,1.d2 \n');
    fprintf(fid,'MQ Minimum Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'Number of Parameters to Treat with Joachimowicz Regularization: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'JW Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'JW Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'5.d0,5.d0,5.d0 \n');
    fprintf(fid,'5.d0,5.d0,5.d0 \n');
    fprintf(fid,'JW Final Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'5.d0,5.d0,5.d0 \n');
    fprintf(fid,'5.d0,5.d0,5.d0 \n');
    fprintf(fid,'Number of Parameters to Treat with Constraints: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Constraint Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'Constraint Weights <converges to exact solution as weight --> inf>: \n');
    fprintf(fid,'1.d-14,1.d-14,1.d-14 \n');
    fprintf(fid,'Constraint Minimums: \n');
    fprintf(fid,'200.d0, 1.d0, 1000.d0, -5.d4, 1000.d0, 0.d0 \n');
    fprintf(fid,'Constraint Maximums: \n');
    fprintf(fid,'5.d5, 5.d5, 1000.d0, -1.d-2, 1.d12, 0.d0 \n');
    fprintf(fid,'CG Residual Scaling Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'0.04d0,0.04d0,0.04d0 \n');
    fprintf(fid,'0.04d0,0.04d0,0.04d0 \n');
    fprintf(fid,'CG Residual Scaling Final Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'0.01d0,0.01d0,0.01d0 \n');
    fprintf(fid,'0.01d0,0.01d0,0.01d0 \n');
    fprintf(fid,'Van Houten Regularization Level: \n');
    fprintf(fid,'1.2d0 \n');
    fprintf(fid,'Number of parameters to treat with soft prior: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'SP Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'SP Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'SP Final Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'SP start iteration delay (first N iterations do not use soft prior \n');
    fprintf(fid,'0 \n');
    fclose(fid);


    %% MREv9 runfile
    % High resolution Iso incompressible run file - viscoelastic - No soft Prior
    viscoutputfv9isoincomp_highres=[outstm  '_G' sprintf('%0.0f',muest) '.v9.hex.inv.iso.incomp.visc_SPoff_SF0p0008_CG4p4_TV5en17'];
    viscrfilev9_highres='runfile-v9_visc_incomp_highres.dat';
    
    ifile=ifile+1;
    filelist(ifile).runf=viscrfilev9_highres;
    filelist(ifile).outf=viscoutputfv9isoincomp_highres;
    filelist(ifile).decription='MRE v9, soft prior off, isotropic VE incompressible - High Resolution';    
    
    fid=fopen([inpath viscrfilev9_highres],'w');
    fprintf(fid,'Subzone Reconstruction Data File \n');
    fprintf(fid,'Problem Type <0=Forward Problem Only> <1+=Inverse Problem> \n');
    fprintf(fid,'1 \n');
    fprintf(fid,'Node File: \n');
    fprintf(fid,'%c',nodhmgf);fprintf(fid,'\n');
    fprintf(fid,'Element File: \n');
    fprintf(fid,'%c',elmhmgf);fprintf(fid,'\n');
    fprintf(fid,'Boundary Node File: \n');
    fprintf(fid,'%c',bcoutf);fprintf(fid,'\n');
    fprintf(fid,'Pressure BC file: \n');
    fprintf(fid,'UNUSED');fprintf(fid,'\n');
    fprintf(fid,'Region Stack File: \n');
    fprintf(fid,'%c',regoutf);fprintf(fid,'\n');
    fprintf(fid,'Measured Displacement File: \n');
    fprintf(fid,'%i',Ndisp);fprintf(fid,'\n');
    for idisp=1:Ndisp
        fprintf(fid,'%10.4fd0',freqHz(idisp));fprintf(fid,'\n');
        fprintf(fid,'%c',dspoutf{idisp});fprintf(fid,'\n');
    end
    fprintf(fid,'Initial Solution File: \n');
    fprintf(fid,'0 \n');
    fprintf(fid,'Output File Stem: \n');
    fprintf(fid,'%c',outpath);fprintf(fid,'%c',viscoutputfv9isoincomp_highres);fprintf(fid,'\n');
    fprintf(fid,'Print Detailed Runtime Debugging and Execution Comments <verb> <file>:\n');
    fprintf(fid,'.false.,.false. \n');
    fprintf(fid,'Material Model <1=isotropic> <2=orthotropic> <3=iso compress>  <4=poro>: \n');
    fprintf(fid,'1 \n');
    fprintf(fid,'Number of Material Properties: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Material Description Style <1=nodal> <2=element> [<shear modulus> <density> <bulk modulus>]: \n');
    fprintf(fid,'1,1,1 \n');
    fprintf(fid,'Number of Parameters per Material Point: \n');
    fprintf(fid,'1,1,1 \n');
    fprintf(fid,'Property Scalars: \n');
    fprintf(fid,'%5.0f.d0,%5.0f.d0,%5.0f.d0,%8.5fd0,%10.0f.d0,%7.0f.d0',[muest 2*DR*muest rhoest -1d-1 2*muest*(1+vincomp)/(3*(1-2*vincomp)) 1e-8]);fprintf(fid,'\n');
	fprintf(fid,'Zone displacement boundary condition option: 1=measured data, 2=seperate file (needs disp files on the following lines),3=calculated displacements \n');
    fprintf(fid,'1 \n');
    fprintf(fid,'Multifrequency Indicator \n');
    fprintf(fid,'.false.,.false.,.false. \n');
    fprintf(fid,'Multifrequency Alpha \n');
    fprintf(fid,'0.d0,0.d0,0.d0 \n');
    fprintf(fid,'0.d0,0.d0,0.d0 \n');
    fprintf(fid,'Number of Material Property Mesh Resolutions: \n');
    fprintf(fid,'2 \n');
    fprintf(fid,'Number of material mesh structures \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Material mesh iteration stucture (one less than number of structures)  \n');
    fprintf(fid,'3,6 \n');
    fprintf(fid,'Material Property Mesh Resolutions (x,y,z): \n');
    fprintf(fid,'%9.7f , %9.7f , %9.7f \n',vox);
    fprintf(fid,'%9.7f , %9.7f , %9.7f \n',10.*vox);
    fprintf(fid,'Material Mesh Index (1st line real part, 2nd line imag) \n ');
    fprintf(fid,'1 2 2 \n');
    fprintf(fid,'1 2 2 \n');
    fprintf(fid,'Material Mesh Index (1st line real part, 2nd line imag) \n ');
    fprintf(fid,'1 2 2 \n');
    fprintf(fid,'1 2 2 \n');
    fprintf(fid,'Material Mesh Index (1st line real part, 2nd line imag) \n ');
    fprintf(fid,'1 2 2 \n');
    fprintf(fid,'1 2 2 \n');
    fprintf(fid,'Reconstruction Indicators: \n');
    fprintf(fid,'.true.,.true. \n');
    fprintf(fid,'.false.,.false. \n');
    fprintf(fid,'.false.,.false. \n');
    fprintf(fid,'Property Estimate Variance Calculation: \n');
    fprintf(fid,'.false. \n');
    fprintf(fid,'Global forward solve to check displacement error \n');
    fprintf(fid,'.false. \n');
    fprintf(fid,'Zone Sizes (not including overlap factor, actual size = (1+2*ovlp)*siz) [x y z]: \n');
    fprintf(fid,'%12.5e,%12.5e,%12.5e',znedgelength);fprintf(fid,'\n');
    fprintf(fid,'Zone Overlap Percentage [x y z]: \n');
    fprintf(fid,'%4.3fd0,%4.3fd0,%4.3fd0',znovlp);fprintf(fid,'\n');
    fprintf(fid,'Iteration Limits [global zone]: \n');
    fprintf(fid,'100,1 \n');
    fprintf(fid,'Minimum Parameter Update Size [global zone line]: \n');
    fprintf(fid,'%c','1.d-5, 1d-5, 1.d-5');fprintf(fid,'\n');
    fprintf(fid,'Number of Zone Iteration Structures: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Iteration Limits for Zone Iteration Structures (NOTE:  provide one less limit than # of structures!!!): \n');
    fprintf(fid,'10,85 \n');
    fprintf(fid,'Zone Iteration Structures [<# of CG iters> <# of GN iters> <!!! QN CURRENTLY UNAVAILABLE !!!> <# of line search iters>]: \n');
    fprintf(fid,'1,0,0,1 \n');
    fprintf(fid,'2,0,0,2 \n');
    fprintf(fid,'4,0,0,4 \n');
    fprintf(fid,'Number of Processors per MUMPS Communicator \n');
    fprintf(fid,'1 \n');
    fprintf(fid,'Maximum Amount of RAM per Processor [MB] \n');
    fprintf(fid,'999999999 \n');
    fprintf(fid,'ooooooooooo  REGULARIZATION DESCRIPTORS  ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo \n');
    fprintf(fid,'Regularization Indicators [<TV> <SF> <TK> <MQ> <JW> <constraints> <CG residual> <VH> <McG> <soft prior>]: \n');
    fprintf(fid,'.true.,.true.,.false.,.false.,.false.,.false.,.true.,.true.,.true.,.false. \n');
    fprintf(fid,'Number of constant regularization iterations (final N iterations use final regularization weights) \n');
    fprintf(fid,'30 \n');
    fprintf(fid,'Number of Parameters to Treat with Total Variation: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'TV Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'TV Delta Values: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-19,1.d-19,1.d-19 \n');
    fprintf(fid,'1.d-19,1.d-19,1.d-19 \n');
    fprintf(fid,'TV Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'5.d-17,5.d-17,5.d-17 \n');
    fprintf(fid,'5.d-17,5.d-17,5.d-17 \n');
    fprintf(fid,'TV Final Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'5.d-17,5.d-17,5.d-17 \n');
    fprintf(fid,'5.d-17,5.d-17,5.d-17 \n');
    fprintf(fid,'Number of Parameters to Treat with Spatial Filtering: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'SF Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'SF Gaussian filter initial Widths: <1st line real, 2nd line imag> \n');
    fprintf(fid,'0.003d0,0.003d0,0.003d0 \n');
    fprintf(fid,'0.003d0,0.003d0,0.003d0 \n');
    fprintf(fid,'SF Final Gaussian width: <1st line real, 2nd line imag> \n');
    fprintf(fid,'0.0008d0,0.0008d0,0.0008d0 \n');
    fprintf(fid,'0.0008d0,0.0008d0,0.0008d0 \n');
    fprintf(fid,'Number of Parameters to Treat with Tikhonov Regularization: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'TK Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'TK Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-18,1.d-18,1.d-18 \n');
    fprintf(fid,'1.d-18,1.d-18,1.d-18 \n');
    fprintf(fid,'TK Final Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-18,1.d-18,1.d-18 \n');
    fprintf(fid,'1.d-18,1.d-18,1.d-18 \n');
    fprintf(fid,'Number of Parameters to Treat with Marquardt Regularization: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Distance of alpha from 1 at which MQ weights are adjusted: \n');
    fprintf(fid,'0.25d0 \n');
    fprintf(fid,'MQ Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'MQ Weight Delta: <1st line real, 2nd line imag> \n');
    fprintf(fid,'0.5d0,0.5d0,0.5d0 \n');
    fprintf(fid,'0.5d0,0.5d0,0.5d0 \n');
    fprintf(fid,'MQ Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d2,1.d2,1.d2 \n');
    fprintf(fid,'1.d2,1.d2,1.d2 \n');
    fprintf(fid,'MQ Minimum Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'Number of Parameters to Treat with Joachimowicz Regularization: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'JW Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'JW Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'5.d0,5.d0,5.d0 \n');
    fprintf(fid,'5.d0,5.d0,5.d0 \n');
    fprintf(fid,'JW Final Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'5.d0,5.d0,5.d0 \n');
    fprintf(fid,'5.d0,5.d0,5.d0 \n');
    fprintf(fid,'Number of Parameters to Treat with Constraints: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Constraint Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'Constraint Weights <converges to exact solution as weight --> inf>: \n');
    fprintf(fid,'1.d-14,1.d-14,1.d-14 \n');
    fprintf(fid,'Constraint Minimums: \n');
    fprintf(fid,'200.d0, 1.d0, 1000.d0, -5.d4, 1000.d0, 0.d0 \n');
    fprintf(fid,'Constraint Maximums: \n');
    fprintf(fid,'5.d5, 5.d5, 1000.d0, -1.d-2, 1.d12, 0.d0 \n');
    fprintf(fid,'CG Residual Scaling Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'0.04d0,0.04d0,0.04d0 \n');
    fprintf(fid,'0.04d0,0.04d0,0.04d0 \n');
    fprintf(fid,'CG Residual Scaling Final Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'0.01d0,0.01d0,0.01d0 \n');
    fprintf(fid,'0.01d0,0.01d0,0.01d0 \n');
    fprintf(fid,'Van Houten Regularization Level: \n');
    fprintf(fid,'1.2d0 \n');
    fprintf(fid,'Number of parameters to treat with soft prior: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'SP Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'SP Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'SP Final Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'SP start iteration delay (first N iterations do not use soft prior \n');
    fprintf(fid,'0 \n');
    fclose(fid);

    
    %% MREv9 runfile
    % Iso compressible run file - viscoelastic - No soft Prior
    viscoutputfv9isocomp_noSP=[outstm  '_G' sprintf('%0.0f',muest) '.v9.inv.iso.comp.visc_SPoff_SF0p0015_CG2p2'];
    viscrfilev9_compnoSP='runfile-v9_visc_comp.dat';
    
    ifile=ifile+1;
    filelist(ifile).runf=viscrfilev9_compnoSP;
    filelist(ifile).outf=viscoutputfv9isocomp_noSP;
    filelist(ifile).decription='MRE v9, soft prior off, isotropic VE compressible';
    
    fid=fopen([inpath viscrfilev9_compnoSP],'w');
    fprintf(fid,'Subzone Reconstruction Data File \n');
    fprintf(fid,'Problem Type <0=Forward Problem Only> <1+=Inverse Problem> \n');
    fprintf(fid,'1 \n');
    fprintf(fid,'Node File: \n');
    fprintf(fid,'%c',nodhmgf);fprintf(fid,'\n');
    fprintf(fid,'Element File: \n');
    fprintf(fid,'%c',elmhmgf);fprintf(fid,'\n');
    fprintf(fid,'Boundary Node File: \n');
    fprintf(fid,'%c',bcoutf);fprintf(fid,'\n');
    fprintf(fid,'Pressure BC file: \n');
    fprintf(fid,'UNUSED');fprintf(fid,'\n');
    fprintf(fid,'Region Stack File: \n');
    fprintf(fid,'%c',regoutf);fprintf(fid,'\n');
    fprintf(fid,'Measured Displacement File: \n');
    fprintf(fid,'%i',Ndisp);fprintf(fid,'\n');
    for idisp=1:Ndisp
        fprintf(fid,'%10.4fd0',freqHz(idisp));fprintf(fid,'\n');
        fprintf(fid,'%c',dspoutf{idisp});fprintf(fid,'\n');
    end
    fprintf(fid,'Initial Solution File: \n');
    fprintf(fid,'0 \n');
    fprintf(fid,'Output File Stem: \n');
    fprintf(fid,'%c',outpath);fprintf(fid,'%c',viscoutputfv9isocomp_noSP);fprintf(fid,'\n');
    fprintf(fid,'Print Detailed Runtime Debugging and Execution Comments <verb> <file>:\n');
    fprintf(fid,'.false.,.false. \n');
    fprintf(fid,'Material Model <1=isotropic> <2=orthotropic> <3=iso compress>  <4=poro>: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Number of Material Properties: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Material Description Style <1=nodal> <2=element> [<shear modulus> <density> <Lambda modulus>]: \n');
    fprintf(fid,'1,1,1 \n');
    fprintf(fid,'Number of Parameters per Material Point: \n');
    fprintf(fid,'1,1,1 \n');
    fprintf(fid,'Property Scalars: \n');
    fprintf(fid,'%5.0f.d0,%5.0f.d0,%5.0f.d0,%8.5fd0,%10.0f.d0,%7.0f.d0',[muest 2*DR*muest rhoest -1d-1 2*muest*vcomp/(3*(1-2*vcomp)) 1e-8]);fprintf(fid,'\n');
	fprintf(fid,'Zone displacement boundary condition option: 1=measured data, 2=seperate file (needs disp files on the following lines),3=calculated displacements \n');
    fprintf(fid,'1 \n');
    fprintf(fid,'Multifrequency Indicator \n');
    fprintf(fid,'.false.,.false.,.false. \n');
    fprintf(fid,'Multifrequency Alpha \n');
    fprintf(fid,'0.d0,0.d0,0.d0 \n');
    fprintf(fid,'0.d0,0.d0,0.d0 \n');
    fprintf(fid,'Number of Material Property Mesh Resolutions: \n');
    fprintf(fid,'2 \n');
    fprintf(fid,'Number of material mesh structures \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Material mesh iteration stucture (one less than number of structures)  \n');
    fprintf(fid,'3,6 \n');
    fprintf(fid,'Material Property Mesh Resolutions (x,y,z): \n');
    fprintf(fid,'%9.7f , %9.7f , %9.7f \n',vox);
    fprintf(fid,'%9.7f , %9.7f , %9.7f \n',10.*vox);
    fprintf(fid,'Material Mesh Index (1st line real part, 2nd line imag) \n ');
    fprintf(fid,'1 2 1 \n');
    fprintf(fid,'1 2 2 \n');
    fprintf(fid,'Material Mesh Index (1st line real part, 2nd line imag) \n ');
    fprintf(fid,'1 2 1 \n');
    fprintf(fid,'1 2 2 \n');
    fprintf(fid,'Material Mesh Index (1st line real part, 2nd line imag) \n ');
    fprintf(fid,'1 2 1 \n');
    fprintf(fid,'1 2 2 \n');
    fprintf(fid,'Reconstruction Indicators: \n');
    fprintf(fid,'.true.,.true. \n');
    fprintf(fid,'.false.,.false. \n');
    fprintf(fid,'.true.,.false. \n');
    fprintf(fid,'Property Estimate Variance Calculation: \n');
    fprintf(fid,'.false. \n');
    fprintf(fid,'Global forward solve to check displacement error \n');
    fprintf(fid,'.false. \n');
    fprintf(fid,'Zone Sizes (not including overlap factor, actual size = (1+2*ovlp)*siz) [x y z]: \n');
    fprintf(fid,'%12.5e,%12.5e,%12.5e',znedgelength);fprintf(fid,'\n');
    fprintf(fid,'Zone Overlap Percentage [x y z]: \n');
    fprintf(fid,'%4.3fd0,%4.3fd0,%4.3fd0',znovlp);fprintf(fid,'\n');
    fprintf(fid,'Iteration Limits [global zone]: \n');
    fprintf(fid,'100,1 \n');
    fprintf(fid,'Minimum Parameter Update Size [global zone line]: \n');
    fprintf(fid,'%c','1.d-5, 1d-5, 1.d-5');fprintf(fid,'\n');
    fprintf(fid,'Number of Zone Iteration Structures: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Iteration Limits for Zone Iteration Structures (NOTE:  provide one less limit than # of structures!!!): \n');
    fprintf(fid,'10,150 \n');
    fprintf(fid,'Zone Iteration Structures [<# of CG iters> <# of GN iters> <!!! QN CURRENTLY UNAVAILABLE !!!> <# of line search iters>]: \n');
    fprintf(fid,'1,0,0,1 \n');
    fprintf(fid,'2,0,0,2 \n');
    fprintf(fid,'3,0,0,2 \n');
    fprintf(fid,'Number of Processors per MUMPS Communicator \n');
    fprintf(fid,'1 \n');
    fprintf(fid,'Maximum Amount of RAM per Processor [MB] \n');
    fprintf(fid,'999999999 \n');
    fprintf(fid,'ooooooooooo  REGULARIZATION DESCRIPTORS  ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo \n');
    fprintf(fid,'Regularization Indicators [<TV> <SF> <TK> <MQ> <JW> <constraints> <CG residual> <VH> <McG> <soft prior>]: \n');
    fprintf(fid,'.false.,.true.,.false.,.false.,.false.,.false.,.true.,.true.,.true.,.false. \n');
    fprintf(fid,'Number of constant regularization iterations (final N iterations use final regularization weights) \n');
    fprintf(fid,'30 \n');
    fprintf(fid,'Number of Parameters to Treat with Total Variation: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'TV Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'TV Delta Values: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-19,1.d-19,1.d-19 \n');
    fprintf(fid,'1.d-19,1.d-19,1.d-19 \n');
    fprintf(fid,'TV Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'5.d-16,5.d-16,5.d-16 \n');
    fprintf(fid,'5.d-16,5.d-16,5.d-16 \n');
    fprintf(fid,'TV Final Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'5.d-16,5.d-16,5.d-16 \n');
    fprintf(fid,'5.d-16,5.d-16,5.d-16 \n');
    fprintf(fid,'Number of Parameters to Treat with Spatial Filtering: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'SF Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'SF Gaussian filter initial Widths: <1st line real, 2nd line imag> \n');
    fprintf(fid,'0.003d0,0.003d0,0.003d0 \n');
    fprintf(fid,'0.003d0,0.003d0,0.003d0 \n');
    fprintf(fid,'SF Final Gaussian width: <1st line real, 2nd line imag> \n');
    fprintf(fid,'0.0015d0,0.0015d0,0.0015d0 \n');
    fprintf(fid,'0.0015d0,0.0015d0,0.0015d0 \n');
    fprintf(fid,'Number of Parameters to Treat with Tikhonov Regularization: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'TK Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'TK Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-18,1.d-18,1.d-18 \n');
    fprintf(fid,'1.d-18,1.d-18,1.d-18 \n');
    fprintf(fid,'TK Final Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-18,1.d-18,1.d-18 \n');
    fprintf(fid,'1.d-18,1.d-18,1.d-18 \n');
    fprintf(fid,'Number of Parameters to Treat with Marquardt Regularization: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Distance of alpha from 1 at which MQ weights are adjusted: \n');
    fprintf(fid,'0.25d0 \n');
    fprintf(fid,'MQ Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'MQ Weight Delta: <1st line real, 2nd line imag> \n');
    fprintf(fid,'0.5d0,0.5d0,0.5d0 \n');
    fprintf(fid,'0.5d0,0.5d0,0.5d0 \n');
    fprintf(fid,'MQ Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d2,1.d2,1.d2 \n');
    fprintf(fid,'1.d2,1.d2,1.d2 \n');
    fprintf(fid,'MQ Minimum Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'Number of Parameters to Treat with Joachimowicz Regularization: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'JW Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'JW Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'5.d0,5.d0,5.d0 \n');
    fprintf(fid,'5.d0,5.d0,5.d0 \n');
    fprintf(fid,'JW Final Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'5.d0,5.d0,5.d0 \n');
    fprintf(fid,'5.d0,5.d0,5.d0 \n');
    fprintf(fid,'Number of Parameters to Treat with Constraints: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Constraint Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'Constraint Weights <converges to exact solution as weight --> inf>: \n');
    fprintf(fid,'1.d-14,1.d-14,1.d-14 \n');
    fprintf(fid,'Constraint Minimums: \n');
    fprintf(fid,'200.d0, 1.d0, 1000.d0, -5.d4, 1000.d0, 0.d0 \n');
    fprintf(fid,'Constraint Maximums: \n');
    fprintf(fid,'5.d5, 5.d5, 1000.d0, -1.d-2, 1.d12, 0.d0 \n');
    fprintf(fid,'CG Residual Scaling Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'0.04d0,0.04d0,0.04d0 \n');
    fprintf(fid,'0.04d0,0.04d0,0.04d0 \n');
    fprintf(fid,'CG Residual Scaling Final Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'0.01d0,0.01d0,0.01d0 \n');
    fprintf(fid,'0.01d0,0.01d0,0.01d0 \n');
    fprintf(fid,'Van Houten Regularization Level: \n');
    fprintf(fid,'1.2d0 \n');
    fprintf(fid,'Number of parameters to treat with soft prior: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'SP Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'SP Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'SP Final Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'SP start iteration delay (first N iterations do not use soft prior \n');
    fprintf(fid,'0 \n');
    fclose(fid);


    



end

