function output_runfiles_tet_v9_mcilvain(outstm,vox,muest,rhoest,DR,inpath,nodhmgf,elmhmgf,bcoutf,regoutf,pbcf,freqHz,dspoutf,outpath,znedgelength,znovlp,noreg,noDTI,SubjectName)
%UNTITLED3 Summary of this function goes here
%   Detailed explanation goes here

vincomp=0.499; % Default Incompressible Poisson Ratio
vcomp=0.4; % Default compressible Poisson ratio


%% MREv9 runfile
    % Poroelastic run file - No soft Prior
    porooutputfv9_noSP=[outstm  '_G' sprintf('%0.0f',muest) '.v9.inv.tet.poro_SPoff_SF0p0015_CG2p2'];
    pororfilev9_noSP='runfile-v9_poro.dat';
    fid=fopen([inpath pororfilev9_noSP],'w');
    fprintf(fid,'Subzone Reconstruction Data File \n');
    fprintf(fid,'Problem Type <0=Forward Problem Only> <1+=Inverse Problem> \n');
    fprintf(fid,'1 \n');
    fprintf(fid,'Node File: \n');
    fprintf(fid,'%c',nodhmgf);fprintf(fid,'\n');
    fprintf(fid,'Element File: \n');
    fprintf(fid,'%c',elmhmgf);fprintf(fid,'\n');
    fprintf(fid,'Boundary Node File: \n');
    fprintf(fid,'%c',bcoutf);fprintf(fid,'\n');
    fprintf(fid,'Pressure Boundary condition file (format: <#nbc, bnod, typ, realval, imagval>) \n');
    fprintf(fid,'%c',pbcf);fprintf(fid,'\n');
    fprintf(fid,'Region Stack File: \n');
    fprintf(fid,'%c',regoutf);fprintf(fid,'\n');
    fprintf(fid,'Measured Displacement File: \n');
    fprintf(fid,'1 \n');
    fprintf(fid,'%10.4fd0',freqHz);fprintf(fid,'\n');
    fprintf(fid,'%c',dspoutf);fprintf(fid,'\n');
    fprintf(fid,'Initial Solution File: \n');
    fprintf(fid,'0 \n');
    fprintf(fid,'Output File Stem: \n');
    fprintf(fid,'%c',outpath);fprintf(fid,'%c',porooutputfv9_noSP);fprintf(fid,'\n');
    fprintf(fid,'Print Detailed Runtime Debugging and Execution Comments <verb> <file>:\n');
    fprintf(fid,'.false.,.false. \n');
    fprintf(fid,'Material Model <1=isotropic> <2=orthotropic> <3=iso compress>  <4=poro>: \n');
    fprintf(fid,'4 \n');
    fprintf(fid,'Number of Material Properties: \n');
    fprintf(fid,'4 \n');
    fprintf(fid,'Material Description Style <1=nodal> <2=element> [<shear modulus> <lambda modulus> <log10(HC)> <porosity>]: \n');
    fprintf(fid,'1,1,1,1 \n');
    fprintf(fid,'Number of Parameters per Material Point: \n');
    fprintf(fid,'1,1,1,1 \n');
    fprintf(fid,'Property Scalars: \n');
    fprintf(fid,'%5.0f.d0,%9.5fd0,%9.3fd0,%9.5fd0,%10.5fd0,%10.5fd0,%7.3fd0,%9.5fd0',[muest 0.0001 2*muest*vcomp/(3*(1-2*vincomp)) 0.0001 -8 -24 0.2 0.0001]);fprintf(fid,'\n');
    fprintf(fid,'Other Poroealstic constants assumed constant <rho, rhof, rhoa> \n');
    fprintf(fid,'1020.d0, 1000.d0, 150.d0 \n');
    fprintf(fid,'Zone displacement boundary condition option: 1=measured data, 2=seperate file (needs disp files on the following lines),3=calculated displacements \n');
    fprintf(fid,'1 \n');
    fprintf(fid,'Poroelastic zone pressure option <1:p=0, 2=pressure fwd prob, 3=global forward solve, 4=from file (needs pressure files on following lines)> \n');
    fprintf(fid,'2 \n'); 
    fprintf(fid,'Poroelastic fluid source file <.true.,.false.> Followed by filenames if true \n');
    fprintf(fid,'.false. \n'); 
    fprintf(fid,'Multifrequency Indicator \n');
    fprintf(fid,'.false.,.false.,.false.,.false. \n');
    fprintf(fid,'Multifrequency Alpha \n');
    fprintf(fid,'0.d0,0.d0,0.d0 ,0.d0\n');
    fprintf(fid,'0.d0,0.d0,0.d0 ,0.d0\n');
    fprintf(fid,'Number of Material Property Mesh Resolutions: \n');
    fprintf(fid,'2 \n');
    fprintf(fid,'Number of material mesh structures \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Material mesh iteration stucture (one less than number of structures)  \n');
    fprintf(fid,'3,6 \n');
    fprintf(fid,'Material Property Mesh Resolutions (x,y,z): \n');
    fprintf(fid,'%9.7f , %9.7f , %9.7f \n',vox);
    fprintf(fid,'%9.7f , %9.7f , %9.7f \n',10.*vox);
    fprintf(fid,'Material Mesh Index (1st line real part, 2nd line imag) \n ');
    fprintf(fid,'1 1 2 2 \n');
    fprintf(fid,'2 2 2 2 \n');
    fprintf(fid,'Material Mesh Index (1st line real part, 2nd line imag) \n ');
    fprintf(fid,'1 1 2 2 \n');
    fprintf(fid,'2 2 2 2 \n');
    fprintf(fid,'Material Mesh Index (1st line real part, 2nd line imag) \n ');
    fprintf(fid,'1 1 2 2 \n');
    fprintf(fid,'2 2 2 2 \n');
    fprintf(fid,'Reconstruction Indicators: \n');
    fprintf(fid,'.true.,.false. \n');
    fprintf(fid,'.true.,.false. \n');
    fprintf(fid,'.false.,.false. \n');
    fprintf(fid,'.false.,.false. \n');
    fprintf(fid,'Property Estimate Variance Calculation: \n');
    fprintf(fid,'.false. \n');
    fprintf(fid,'Global forward solve to check displacement error \n');
    fprintf(fid,'.false. \n');
    fprintf(fid,'Zone Sizes (not including overlap factor, actual size = (1+2*ovlp)*siz) [x y z]: \n');
    fprintf(fid,'%12.5e,%12.5e,%12.5e',znedgelength);fprintf(fid,'\n');
    fprintf(fid,'Zone Overlap Percentage [x y z]: \n');
    fprintf(fid,'%4.3fd0,%4.3fd0,%4.3fd0',znovlp);fprintf(fid,'\n');
    fprintf(fid,'Iteration Limits [global zone]: \n');
    fprintf(fid,'100,1 \n');
    fprintf(fid,'Minimum Parameter Update Size [global zone line]: \n');
    fprintf(fid,'%c','0.1d0, 0.1d0, 0.1d0');fprintf(fid,'\n');
    fprintf(fid,'Number of Zone Iteration Structures: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Iteration Limits for Zone Iteration Structures (NOTE:  provide one less limit than # of structures!!!): \n');
    fprintf(fid,'10,150 \n');
    fprintf(fid,'Zone Iteration Structures [<# of CG iters> <# of GN iters> <!!! QN CURRENTLY UNAVAILABLE !!!> <# of line search iters>]: \n');
    fprintf(fid,'1,0,0,1 \n');
    fprintf(fid,'2,0,0,2 \n');
    fprintf(fid,'3,0,0,2 \n');
    fprintf(fid,'Number of Processors per MUMPS Communicator \n');
    fprintf(fid,'1 \n');
    fprintf(fid,'Maximum Amount of RAM per Processor [MB] \n');
    fprintf(fid,'999999999 \n');
    fprintf(fid,'ooooooooooo  REGULARIZATION DESCRIPTORS  ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo \n');
    fprintf(fid,'Regularization Indicators [<TV> <SF> <TK> <MQ> <JW> <constraints> <CG residual> <VH> <McG> <soft prior>]: \n');
    fprintf(fid,'.false.,.true.,.false.,.false.,.false.,.false.,.true.,.true.,.true.,.false. \n');
    fprintf(fid,'Number of constant regularization iterations (final N iterations use final regularization weights) \n');
    fprintf(fid,'30 \n');
    fprintf(fid,'Number of Parameters to Treat with Total Variation: \n');
    fprintf(fid,'4 \n');
    fprintf(fid,'TV Parameter List: \n');
    fprintf(fid,'1,2,3,4 \n');
    fprintf(fid,'TV Delta Values: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-19,1.d-19,1.d-19,1.d-19 \n');
    fprintf(fid,'1.d-19,1.d-19,1.d-19,1.d-19 \n');
    fprintf(fid,'TV Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'5.d-16,5.d-16,5.d-16,5.d-16 \n');
    fprintf(fid,'5.d-16,5.d-16,5.d-16,5.d-16 \n');
    fprintf(fid,'TV Final Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'5.d-16,5.d-16,5.d-16,5.d-16 \n');
    fprintf(fid,'5.d-16,5.d-16,5.d-16,5.d-16 \n');
    fprintf(fid,'Number of Parameters to Treat with Spatial Filtering: \n');
    fprintf(fid,'4 \n');
    fprintf(fid,'SF Parameter List: \n');
    fprintf(fid,'1,2,3,4 \n');
    fprintf(fid,'SF Gaussian filter initial Widths: <1st line real, 2nd line imag> \n');
    fprintf(fid,'0.003d0,0.003d0,0.003d0,0.003d0 \n');
    fprintf(fid,'0.003d0,0.003d0,0.003d0,0.003d0 \n');
    fprintf(fid,'SF Final Gaussian width: <1st line real, 2nd line imag> \n');
    fprintf(fid,'0.0015d0,0.0015d0,0.0015d0,0.0015d0 \n');
    fprintf(fid,'0.0015d0,0.0015d0,0.0015d0,0.0015d0 \n');
    fprintf(fid,'Number of Parameters to Treat with Tikhonov Regularization: \n');
    fprintf(fid,'4 \n');
    fprintf(fid,'TK Parameter List: \n');
    fprintf(fid,'1,2,3,4 \n');
    fprintf(fid,'TK Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-18,1.d-18,1.d-18,1.d-18 \n');
    fprintf(fid,'1.d-18,1.d-18,1.d-18,1.d-18 \n');
    fprintf(fid,'TK Final Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-18,1.d-18,1.d-18,1.d-18 \n');
    fprintf(fid,'1.d-18,1.d-18,1.d-18,1.d-18 \n');
    fprintf(fid,'Number of Parameters to Treat with Marquardt Regularization: \n');
    fprintf(fid,'4 \n');
    fprintf(fid,'Distance of alpha from 1 at which MQ weights are adjusted: \n');
    fprintf(fid,'0.25d0 \n');
    fprintf(fid,'MQ Parameter List: \n');
    fprintf(fid,'1,2,3,4 \n');
    fprintf(fid,'MQ Weight Delta: <1st line real, 2nd line imag> \n');
    fprintf(fid,'0.5d0,0.5d0,0.5d0,0.5d0 \n');
    fprintf(fid,'0.5d0,0.5d0,0.5d0,0.5d0 \n');
    fprintf(fid,'MQ Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d2,1.d2,1.d2,1.d2 \n');
    fprintf(fid,'1.d2,1.d2,1.d2,1.d2 \n');
    fprintf(fid,'MQ Minimum Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'Number of Parameters to Treat with Joachimowicz Regularization: \n');
    fprintf(fid,'4 \n');
    fprintf(fid,'JW Parameter List: \n');
    fprintf(fid,'1,2,3,4 \n');
    fprintf(fid,'JW Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'5.d0,5.d0,5.d0,5.d0 \n');
    fprintf(fid,'5.d0,5.d0,5.d0,5.d0 \n');
    fprintf(fid,'JW Final Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'5.d0,5.d0,5.d0,5.d0 \n');
    fprintf(fid,'5.d0,5.d0,5.d0,5.d0 \n');
    fprintf(fid,'Number of Parameters to Treat with Constraints: \n');
    fprintf(fid,'4 \n');
    fprintf(fid,'Constraint Parameter List: \n');
    fprintf(fid,'1,2,3,4 \n');
    fprintf(fid,'Constraint Weights <converges to exact solution as weight --> inf>: \n');
    fprintf(fid,'1.d-14,1.d-14,1.d-14,1.d-14 \n');
    fprintf(fid,'Constraint Minimums: \n');
    fprintf(fid,'200.d0, 0.d0, 1000.d0, 0.d0, -25 -25 0.001 0.d0 \n');
    fprintf(fid,'Constraint Maximums: \n');
    fprintf(fid,'5.d5, 5.d5, 5.d6, 5.d6, -5.d0, -5.d0, 0.8 0.8 \n');
    fprintf(fid,'CG Residual Scaling Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'0.04d0,0.04d0,0.04d0,0.04d0 \n');
    fprintf(fid,'0.04d0,0.04d0,0.04d0,0.04d0 \n');
    fprintf(fid,'CG Residual Scaling Final Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'0.01d0,0.01d0,0.01d0,0.01d0 \n');
    fprintf(fid,'0.01d0,0.01d0,0.01d0,0.01d0 \n');
    fprintf(fid,'Van Houten Regularization Level: \n');
    fprintf(fid,'1.2d0 \n');
    fprintf(fid,'Number of parameters to treat with soft prior: \n');
    fprintf(fid,'4 \n');
    fprintf(fid,'SP Parameter List: \n');
    fprintf(fid,'1,2,3,4 \n');
    fprintf(fid,'SP Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'SP Final Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'SP start iteration delay (first N iterations do not use soft prior \n');
    fprintf(fid,'0 \n');
    fclose(fid);
    
      
    % Build MRE-submit file
    viscsubnamev9='McIlvain-Submitv9_poro';
        runfile_dir = ['/insomnia001/depts/mcilvain/users/mcilvain/', SubjectName, '/hex/', SubjectName, '_voxelmesh'];

    fid=fopen([inpath viscsubnamev9],'w');
    %mvfiles(length(mvfiles)+1).name=viscsubnamev7p3_noSP;
    fprintf(fid,'#!/bin/bash -l \n');
    fprintf(fid,'#SBATCH --account=mcilvain \n');
    fprintf(fid,'#SBATCH --job-name=mre_processing \n');
    fprintf(fid,'#SBATCH --time=10:00:00 \n');
    fprintf(fid,'#SBATCH --ntasks=30 \n');
    fprintf(fid,'#SBATCH --cpus-per-task=1 \n');
    fprintf(fid,'#SBATCH --mem=60G \n');
    fprintf(fid,'#SBATCH --partition=standard \n');

    fprintf(fid,'SIF_PATH="/insomnia001/depts/mcilvain/projects/NLI/mre-neuro-processing-final.sif" \n');
    fprintf(fid, 'RUNFILE_DIR="%s" \n', runfile_dir);
    fprintf(fid,'RUNFILE="runfile-v9_poro.dat" \n');
     fprintf(fid, 'cd "$RUNFILE_DIR" \n');
    fprintf(fid, 'apptainer exec --bind "$RUNFILE_DIR":/mnt "$SIF_PATH" bash -c ');
    fprintf(fid, '''export I_MPI_FABRICS=shm:ofi && /opt/intel/oneapi/mpi/bin/mpiexec.hydra -n 30 /MREv9p37a/MRE-Zone.discov /mnt/''"$RUNFILE"\n');
    fprintf(fid,'date \n');
    fprintf(fid,'## auto post processing \n');
    fprintf(fid,'srchtag=*RE..*0001*prop.01.mtr\n');
    fprintf(fid,'outstm=$(sed ''21!d'' runfile-v9_visc_incomp)\n');
    fprintf(fid, 'cd inv \n');
    fprintf(fid,'/insomnia001/depts/mcilvain/projects/Code/MREpostprocess/MREpostprocessv8.x $srchtag');fprintf(fid,'\n');
    fprintf(fid,'exit 0  \n');
    fclose(fid);


    
    
    % Tetvisc mesh files
    %% MREv9 runfile
    % Tetrahedral viscoealstic run file - No soft Prior
    tetviscoutputfv9_noSP=[outstm  '_G' sprintf('%0.0f',muest) '.v9.inv.tet.visc_SPoff_SF0p0015_CG2p2'];
    tetviscrfilev9_noSP='runfile-v9_tetvisc.dat';
    fid=fopen([inpath tetviscrfilev9_noSP],'w');
    fprintf(fid,'Subzone Reconstruction Data File \n');
    fprintf(fid,'Problem Type <0=Forward Problem Only> <1+=Inverse Problem> \n');
    fprintf(fid,'1 \n');
    fprintf(fid,'Node File: \n');
    fprintf(fid,'%c',nodhmgf);fprintf(fid,'\n');
    fprintf(fid,'Element File: \n');
    fprintf(fid,'%c',elmhmgf);fprintf(fid,'\n');
    fprintf(fid,'Boundary Node File: \n');
    fprintf(fid,'%c',bcoutf);fprintf(fid,'\n');
    fprintf(fid,'Pressure BC file: \n');
    fprintf(fid,'UNUSED');fprintf(fid,'\n');
    fprintf(fid,'Region Stack File: \n');
    fprintf(fid,'%c',regoutf);fprintf(fid,'\n');
    fprintf(fid,'Measured Displacement File: \n');
    fprintf(fid,'1 \n');
    fprintf(fid,'%10.4fd0',freqHz);fprintf(fid,'\n');
    fprintf(fid,'%c',dspoutf);fprintf(fid,'\n');
    fprintf(fid,'Initial Solution File: \n');
    fprintf(fid,'0 \n');
    fprintf(fid,'Output File Stem: \n');
    fprintf(fid,'%c',outpath);fprintf(fid,'%c',tetviscoutputfv9_noSP);fprintf(fid,'\n');
    fprintf(fid,'Print Detailed Runtime Debugging and Execution Comments <verb> <file>:\n');
    fprintf(fid,'.false.,.false. \n');
    fprintf(fid,'Material Model <1=isotropic> <2=orthotropic> <3=iso compress> <4=poro>: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Number of Material Properties: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Material Description Style <1=nodal> <2=element> [<shear modulus> <density> <Lambda modulus>]: \n');
    fprintf(fid,'1,1,1 \n');
    fprintf(fid,'Number of Parameters per Material Point: \n');
    fprintf(fid,'1,1,1 \n');
    fprintf(fid,'Property Scalars: \n');
    fprintf(fid,'%5.0f.d0,%5.0f.d0,%5.0f.d0,%8.5fd0,%10.0f.d0,%8.5fd0',[muest 2*DR*muest rhoest -1d-1 2*muest*vcomp/(3*(1-2*vcomp)) 0.0001]);fprintf(fid,'\n');
    fprintf(fid,'Zone displacement boundary condition option: 1=measured data, 2=seperate file (needs disp files on the following lines),3=calculated displacements \n');
    fprintf(fid,'1 \n');
    fprintf(fid,'Multifrequency Indicator \n');
    fprintf(fid,'.false.,.false.,.false. \n');
    fprintf(fid,'Multifrequency Alpha \n');
    fprintf(fid,'0.d0,0.d0,0.d0 \n');
    fprintf(fid,'0.d0,0.d0,0.d0 \n');
    fprintf(fid,'Number of Material Property Mesh Resolutions: \n');
    fprintf(fid,'2 \n');
    fprintf(fid,'Number of material mesh structures \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Material mesh iteration stucture (one less than number of structures)  \n');
    fprintf(fid,'3,6 \n');
    fprintf(fid,'Material Property Mesh Resolutions (x,y,z): \n');
    fprintf(fid,'%9.7f , %9.7f , %9.7f \n',vox);
    fprintf(fid,'%9.7f , %9.7f , %9.7f \n',10.*vox);
    fprintf(fid,'Material Mesh Index (1st line real part, 2nd line imag) \n ');
    fprintf(fid,'1 2 1 \n');
    fprintf(fid,'1 2 1 \n');
    fprintf(fid,'Material Mesh Index (1st line real part, 2nd line imag) \n ');
    fprintf(fid,'1 2 1 \n');
    fprintf(fid,'1 2 1 \n');
    fprintf(fid,'Material Mesh Index (1st line real part, 2nd line imag) \n ');
    fprintf(fid,'1 2 1 \n');
    fprintf(fid,'1 2 1 \n');
    fprintf(fid,'Reconstruction Indicators: \n');
    fprintf(fid,'.true.,.true. \n');
    fprintf(fid,'.false.,.false. \n');
    fprintf(fid,'.true.,.false. \n');
    fprintf(fid,'Property Estimate Variance Calculation: \n');
    fprintf(fid,'.false. \n');
    fprintf(fid,'Global forward solve to check displacement error \n');
    fprintf(fid,'.false. \n');
    fprintf(fid,'Zone Sizes (not including overlap factor, actual size = (1+2*ovlp)*siz) [x y z]: \n');
    fprintf(fid,'%12.5e,%12.5e,%12.5e',znedgelength);fprintf(fid,'\n');
    fprintf(fid,'Zone Overlap Percentage [x y z]: \n');
    fprintf(fid,'%4.3fd0,%4.3fd0,%4.3fd0',znovlp);fprintf(fid,'\n');
    fprintf(fid,'Iteration Limits [global zone]: \n');
    fprintf(fid,'100,1 \n');
    fprintf(fid,'Minimum Parameter Update Size [global zone line]: \n');
    fprintf(fid,'%c','0.1d0, 0.1d0, 0.1d0');fprintf(fid,'\n');
    fprintf(fid,'Number of Zone Iteration Structures: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Iteration Limits for Zone Iteration Structures (NOTE:  provide one less limit than # of structures!!!): \n');
    fprintf(fid,'10,150 \n');
    fprintf(fid,'Zone Iteration Structures [<# of CG iters> <# of GN iters> <!!! QN CURRENTLY UNAVAILABLE !!!> <# of line search iters>]: \n');
    fprintf(fid,'1,0,0,1 \n');
    fprintf(fid,'2,0,0,2 \n');
    fprintf(fid,'3,0,0,2 \n');
    fprintf(fid,'Number of Processors per MUMPS Communicator \n');
    fprintf(fid,'1 \n');
    fprintf(fid,'Maximum Amount of RAM per Processor [MB] \n');
    fprintf(fid,'999999999 \n');
    fprintf(fid,'ooooooooooo  REGULARIZATION DESCRIPTORS  ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo \n');
    fprintf(fid,'Regularization Indicators [<TV> <SF> <TK> <MQ> <JW> <constraints> <CG residual> <VH> <McG> <soft prior>]: \n');
    fprintf(fid,'.false.,.true.,.false.,.false.,.false.,.false.,.true.,.true.,.true.,.false. \n');
    fprintf(fid,'Number of constant regularization iterations (final N iterations use final regularization weights) \n');
    fprintf(fid,'30 \n');
    fprintf(fid,'Number of Parameters to Treat with Total Variation: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'TV Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'TV Delta Values: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-19,1.d-19,1.d-19 \n');
    fprintf(fid,'1.d-19,1.d-19,1.d-19 \n');
    fprintf(fid,'TV Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'5.d-16,5.d-16,5.d-16 \n');
    fprintf(fid,'5.d-16,5.d-16,5.d-16 \n');
    fprintf(fid,'TV Final Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'5.d-16,5.d-16,5.d-16 \n');
    fprintf(fid,'5.d-16,5.d-16,5.d-16 \n');
    fprintf(fid,'Number of Parameters to Treat with Spatial Filtering: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'SF Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'SF Gaussian filter initial Widths: <1st line real, 2nd line imag> \n');
    fprintf(fid,'0.003d0,0.003d0,0.003d0 \n');
    fprintf(fid,'0.003d0,0.003d0,0.003d0 \n');
    fprintf(fid,'SF Final Gaussian width: <1st line real, 2nd line imag> \n');
    fprintf(fid,'0.0015d0,0.0015d0,0.0015d0 \n');
    fprintf(fid,'0.0015d0,0.0015d0,0.0015d0 \n');
    fprintf(fid,'Number of Parameters to Treat with Tikhonov Regularization: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'TK Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'TK Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-18,1.d-18,1.d-18 \n');
    fprintf(fid,'1.d-18,1.d-18,1.d-18 \n');
    fprintf(fid,'TK Final Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-18,1.d-18,1.d-18 \n');
    fprintf(fid,'1.d-18,1.d-18,1.d-18 \n');
    fprintf(fid,'Number of Parameters to Treat with Marquardt Regularization: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Distance of alpha from 1 at which MQ weights are adjusted: \n');
    fprintf(fid,'0.25d0 \n');
    fprintf(fid,'MQ Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'MQ Weight Delta: <1st line real, 2nd line imag> \n');
    fprintf(fid,'0.5d0,0.5d0,0.5d0 \n');
    fprintf(fid,'0.5d0,0.5d0,0.5d0 \n');
    fprintf(fid,'MQ Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d2,1.d2,1.d2 \n');
    fprintf(fid,'1.d2,1.d2,1.d2 \n');
    fprintf(fid,'MQ Minimum Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'Number of Parameters to Treat with Joachimowicz Regularization: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'JW Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'JW Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'5.d0,5.d0,5.d0 \n');
    fprintf(fid,'5.d0,5.d0,5.d0 \n');
    fprintf(fid,'JW Final Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'5.d0,5.d0,5.d0 \n');
    fprintf(fid,'5.d0,5.d0,5.d0 \n');
    fprintf(fid,'Number of Parameters to Treat with Constraints: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Constraint Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'Constraint Weights <converges to exact solution as weight --> inf>: \n');
    fprintf(fid,'1.d-14,1.d-14,1.d-14 \n');
    fprintf(fid,'Constraint Minimums: \n');
    fprintf(fid,'200.d0, 1.d0, 1000.d0, -5.d4, 1000.d0, 0.d0 \n');
    fprintf(fid,'Constraint Maximums: \n');
    fprintf(fid,'5.d5, 5.d5, 1000.d0, -1.d-2, 1.d12, 0.d0 \n');
    fprintf(fid,'CG Residual Scaling Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'0.04d0,0.04d0,0.04d0 \n');
    fprintf(fid,'0.04d0,0.04d0,0.04d0 \n');
    fprintf(fid,'CG Residual Scaling Final Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'0.01d0,0.01d0,0.01d0 \n');
    fprintf(fid,'0.01d0,0.01d0,0.01d0 \n');
    fprintf(fid,'Van Houten Regularization Level: \n');
    fprintf(fid,'1.2d0 \n');
    fprintf(fid,'Number of parameters to treat with soft prior: \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'SP Parameter List: \n');
    fprintf(fid,'1,2,3 \n');
    fprintf(fid,'SP Initial Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'SP Final Weights: <1st line real, 2nd line imag> \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
    fprintf(fid,'SP start iteration delay (first N iterations do not use soft prior \n');
    fprintf(fid,'0 \n');
    fclose(fid);
    
    % Build MRE-submit file
    viscsubnamev9='McIlvain-Submitv9_tetvisc';
    runfile_dir = ['/insomnia001/depts/mcilvain/users/mcilvain/', SubjectName, '/hex/', SubjectName, '_voxelmesh'];

    fid=fopen([inpath viscsubnamev9],'w');
    %mvfiles(length(mvfiles)+1).name=viscsubnamev7p3_noSP;
    fprintf(fid,'#!/bin/bash -l \n');
    fprintf(fid,'#SBATCH --account=mcilvain \n');
    fprintf(fid,'#SBATCH --job-name=mre_processing \n');
    fprintf(fid,'#SBATCH --time=10:00:00 \n');
    fprintf(fid,'#SBATCH --ntasks=30 \n');
    fprintf(fid,'#SBATCH --cpus-per-task=1 \n');
    fprintf(fid,'#SBATCH --mem=60G \n');
    fprintf(fid,'#SBATCH --partition=standard \n');

    fprintf(fid,'SIF_PATH="/insomnia001/depts/mcilvain/projects/NLI/mre-neuro-processing-final.sif" \n');
    fprintf(fid, 'RUNFILE_DIR="%s" \n', runfile_dir);
    fprintf(fid,'RUNFILE="runfile-v9_tetvisc.dat" \n');
    fprintf(fid, 'cd "$RUNFILE_DIR" \n');
    fprintf(fid, 'apptainer exec --bind "$RUNFILE_DIR":/mnt "$SIF_PATH" bash -c ');
    fprintf(fid, '''export I_MPI_FABRICS=shm:ofi && /opt/intel/oneapi/mpi/bin/mpiexec.hydra -n 30 /MREv9p37a/MRE-Zone.discov /mnt/''"$RUNFILE"\n');
    fprintf(fid,'date \n');
    fprintf(fid,'## auto post processing \n');
    fprintf(fid,'srchtag=*RE..*0001*prop.01.mtr\n');
    fprintf(fid,'outstm=$(sed ''21!d'' runfile-v9_visc_incomp)\n');
    fprintf(fid, 'cd inv \n');
    fprintf(fid,'/insomnia001/depts/mcilvain/projects/Code/MREpostprocess/MREpostprocessv8.x $srchtag');fprintf(fid,'\n');
    fprintf(fid,'exit 0  \n');
    fclose(fid);

    
    if(~noreg) % do not output soft prior runfiles without a supplied segmentation.
        %% MREv9 runfile
        % Poroelastic run file - Yes soft Prior
        porooutputfv9_SP=[outstm  '_G' sprintf('%0.0f',muest) '.v9.inv.tet.poro_SP1en9_SF0p0015_CG2p2'];
        pororfilev9_SP='runfile-v9_poroSP.dat';
        fid=fopen([inpath pororfilev9_SP],'w');
        fprintf(fid,'Subzone Reconstruction Data File \n');
        fprintf(fid,'Problem Type <0=Forward Problem Only> <1+=Inverse Problem> \n');
        fprintf(fid,'1 \n');
        fprintf(fid,'Node File: \n');
        fprintf(fid,'%c',nodhmgf);fprintf(fid,'\n');
        fprintf(fid,'Element File: \n');
        fprintf(fid,'%c',elmhmgf);fprintf(fid,'\n');
        fprintf(fid,'Boundary Node File: \n');
        fprintf(fid,'%c',bcoutf);fprintf(fid,'\n');
        fprintf(fid,'Pressure Boundary condition file (format: <#nbc, bnod, typ, realval, imagval>) \n');
        fprintf(fid,'%c',pbcf);fprintf(fid,'\n');
        fprintf(fid,'Region Stack File: \n');
        fprintf(fid,'%c',regoutf);fprintf(fid,'\n');
        fprintf(fid,'Measured Displacement File: \n');
        fprintf(fid,'1 \n');
        fprintf(fid,'%10.4fd0',freqHz);fprintf(fid,'\n');
        fprintf(fid,'%c',dspoutf);fprintf(fid,'\n');
        fprintf(fid,'Initial Solution File: \n');
        fprintf(fid,'0 \n');
        fprintf(fid,'Output File Stem: \n');
        fprintf(fid,'%c',outpath);fprintf(fid,'%c',porooutputfv9_SP);fprintf(fid,'\n');
        fprintf(fid,'Print Detailed Runtime Debugging and Execution Comments <verb> <file>:\n');
        fprintf(fid,'.false.,.false. \n');
        fprintf(fid,'Material Model <1=isotropic> <2=orthotropic> <3=iso compress>  <4=poro>: \n');
        fprintf(fid,'4 \n');
        fprintf(fid,'Number of Material Properties: \n');
        fprintf(fid,'4 \n');
        fprintf(fid,'Material Description Style <1=nodal> <2=element> [<shear modulus> <lambda modulus> <log10(HC)> <porosity>]: \n');
        fprintf(fid,'1,1,1,1 \n');
        fprintf(fid,'Number of Parameters per Material Point: \n');
        fprintf(fid,'1,1,1,1 \n');
        fprintf(fid,'Property Scalars: \n');
        fprintf(fid,'%5.0f.d0,%8.5fd0,%10.3fd0,%10.3fd0,%10.5fd0,%10.5fd0,%7.3fd0,%9.5fd0',[muest 0.0001 2*muest*vcomp/(3*(1-2*vincomp)) 0.0001 -8 -24 0.2 0.0001]);fprintf(fid,'\n');
        fprintf(fid,'Other Poroealstic constants assumed constant <rho, rhof, rhoa> \n');
        fprintf(fid,'1020.d0, 1000.d0, 150.d0 \n');
        fprintf(fid,'Zone displacement boundary condition option: 1=measured data, 2=seperate file (needs disp files on the following lines),3=calculated displacements \n');
        fprintf(fid,'1 \n');
        fprintf(fid,'Poroelastic zone pressure option <1:p=0, 2=pressure fwd prob, 3=global forward solve, 4=from file (needs pressure files on following lines)> \n');
        fprintf(fid,'2 \n'); 
        fprintf(fid,'Poroelastic fluid source file <.true.,.false.> Followed by filenames if true \n');
        fprintf(fid,'.false. \n');        
        fprintf(fid,'Multifrequency Indicator \n');
        fprintf(fid,'.false.,.false.,.false.,.false. \n');
        fprintf(fid,'Multifrequency Alpha \n');
        fprintf(fid,'0.d0,0.d0,0.d0,0.d0 \n');
        fprintf(fid,'0.d0,0.d0,0.d0,0.d0 \n');
        fprintf(fid,'Number of Material Property Mesh Resolutions: \n');
    fprintf(fid,'2 \n');
    fprintf(fid,'Number of material mesh structures \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Material mesh iteration stucture (one less than number of structures)  \n');
    fprintf(fid,'3,6 \n');
    fprintf(fid,'Material Property Mesh Resolutions (x,y,z): \n');
    fprintf(fid,'%9.7f , %9.7f , %9.7f \n',vox);
    fprintf(fid,'%9.7f , %9.7f , %9.7f \n',10.*vox);
    fprintf(fid,'Material Mesh Index (1st line real part, 2nd line imag) \n ');
    fprintf(fid,'1 1 2 2 \n');
    fprintf(fid,'2 2 2 2 \n');
    fprintf(fid,'Material Mesh Index (1st line real part, 2nd line imag) \n ');
    fprintf(fid,'1 1 2 2 \n');
    fprintf(fid,'2 2 2 2 \n');
    fprintf(fid,'Material Mesh Index (1st line real part, 2nd line imag) \n ');
    fprintf(fid,'1 1 2 2 \n');
    fprintf(fid,'2 2 2 2 \n');
        fprintf(fid,'Reconstruction Indicators: \n');
        fprintf(fid,'.true.,.false. \n');
        fprintf(fid,'.true.,.false. \n');
        fprintf(fid,'.false.,.false. \n');
        fprintf(fid,'.false.,.false. \n');
        fprintf(fid,'Property Estimate Variance Calculation: \n');
        fprintf(fid,'.false. \n');
        fprintf(fid,'Global forward solve to check displacement error \n');
        fprintf(fid,'.false. \n');
        fprintf(fid,'Zone Sizes (not including overlap factor, actual size = (1+2*ovlp)*siz) [x y z]: \n');
        fprintf(fid,'%12.5e,%12.5e,%12.5e',znedgelength);fprintf(fid,'\n');
        fprintf(fid,'Zone Overlap Percentage [x y z]: \n');
        fprintf(fid,'%4.3fd0,%4.3fd0,%4.3fd0',znovlp);fprintf(fid,'\n');
        fprintf(fid,'Iteration Limits [global zone]: \n');
        fprintf(fid,'100,1 \n');
        fprintf(fid,'Minimum Parameter Update Size [global zone line]: \n');
        fprintf(fid,'%c','0.1d0, 0.1d0, 0.1d0');fprintf(fid,'\n');
        fprintf(fid,'Number of Zone Iteration Structures: \n');
        fprintf(fid,'3 \n');
        fprintf(fid,'Iteration Limits for Zone Iteration Structures (NOTE:  provide one less limit than # of structures!!!): \n');
        fprintf(fid,'10,150 \n');
        fprintf(fid,'Zone Iteration Structures [<# of CG iters> <# of GN iters> <!!! QN CURRENTLY UNAVAILABLE !!!> <# of line search iters>]: \n');
        fprintf(fid,'1,0,0,1 \n');
        fprintf(fid,'2,0,0,2 \n');
        fprintf(fid,'3,0,0,2 \n');
        fprintf(fid,'Number of Processors per MUMPS Communicator \n');
        fprintf(fid,'1 \n');
        fprintf(fid,'Maximum Amount of RAM per Processor [MB] \n');
        fprintf(fid,'999999999 \n');
        fprintf(fid,'ooooooooooo  REGULARIZATION DESCRIPTORS  ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo \n');
        fprintf(fid,'Regularization Indicators [<TV> <SF> <TK> <MQ> <JW> <constraints> <CG residual> <VH> <McG> <soft prior>]: \n');
        fprintf(fid,'.false.,.true.,.false.,.false.,.false.,.false.,.true.,.true.,.true.,.true. \n');
        fprintf(fid,'Number of constant regularization iterations (final N iterations use final regularization weights) \n');
        fprintf(fid,'30 \n');
        fprintf(fid,'Number of Parameters to Treat with Total Variation: \n');
        fprintf(fid,'4 \n');
        fprintf(fid,'TV Parameter List: \n');
        fprintf(fid,'1,2,3,4 \n');
        fprintf(fid,'TV Delta Values: <1st line real, 2nd line imag> \n');
        fprintf(fid,'1.d-19,1.d-19,1.d-19,1.d-19 \n');
        fprintf(fid,'1.d-19,1.d-19,1.d-19,1.d-19 \n');
        fprintf(fid,'TV Initial Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'5.d-16,5.d-16,5.d-16,5.d-16 \n');
        fprintf(fid,'5.d-16,5.d-16,5.d-16,5.d-16 \n');
        fprintf(fid,'TV Final Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'5.d-16,5.d-16,5.d-16,5.d-16 \n');
        fprintf(fid,'5.d-16,5.d-16,5.d-16,5.d-16 \n');
        fprintf(fid,'Number of Parameters to Treat with Spatial Filtering: \n');
        fprintf(fid,'4 \n');
        fprintf(fid,'SF Parameter List: \n');
        fprintf(fid,'1,2,3,4 \n');
        fprintf(fid,'SF Gaussian filter initial Widths: <1st line real, 2nd line imag> \n');
        fprintf(fid,'0.003d0,0.003d0,0.003d0,0.003d0 \n');
        fprintf(fid,'0.003d0,0.003d0,0.003d0,0.003d0 \n');
        fprintf(fid,'SF Final Gaussian width: <1st line real, 2nd line imag> \n');
        fprintf(fid,'0.0015d0,0.0015d0,0.0015d0,0.0015d0 \n');
        fprintf(fid,'0.0015d0,0.0015d0,0.0015d0,0.0015d0 \n');
        fprintf(fid,'Number of Parameters to Treat with Tikhonov Regularization: \n');
        fprintf(fid,'4 \n');
        fprintf(fid,'TK Parameter List: \n');
        fprintf(fid,'1,2,3,4 \n');
        fprintf(fid,'TK Initial Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'1.d-18,1.d-18,1.d-18,1.d-18 \n');
        fprintf(fid,'1.d-18,1.d-18,1.d-18,1.d-18 \n');
        fprintf(fid,'TK Final Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'1.d-18,1.d-18,1.d-18,1.d-18 \n');
        fprintf(fid,'1.d-18,1.d-18,1.d-18,1.d-18 \n');
        fprintf(fid,'Number of Parameters to Treat with Marquardt Regularization: \n');
        fprintf(fid,'4 \n');
        fprintf(fid,'Distance of alpha from 1 at which MQ weights are adjusted: \n');
        fprintf(fid,'0.25d0 \n');
        fprintf(fid,'MQ Parameter List: \n');
        fprintf(fid,'1,2,3,4 \n');
        fprintf(fid,'MQ Weight Delta: <1st line real, 2nd line imag> \n');
        fprintf(fid,'0.5d0,0.5d0,0.5d0,0.5d0 \n');
        fprintf(fid,'0.5d0,0.5d0,0.5d0,0.5d0 \n');
        fprintf(fid,'MQ Initial Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'1.d2,1.d2,1.d2,1.d2 \n');
        fprintf(fid,'1.d2,1.d2,1.d2,1.d2 \n');
        fprintf(fid,'MQ Minimum Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'1.d-11,1.d-11,1.d-11,1.d-11 \n');
        fprintf(fid,'1.d-11,1.d-11,1.d-11,1.d-11 \n');
        fprintf(fid,'Number of Parameters to Treat with Joachimowicz Regularization: \n');
        fprintf(fid,'4 \n');
        fprintf(fid,'JW Parameter List: \n');
        fprintf(fid,'1,2,3,4 \n');
        fprintf(fid,'JW Initial Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'5.d0,5.d0,5.d0,5.d0 \n');
        fprintf(fid,'5.d0,5.d0,5.d0,5.d0 \n');
        fprintf(fid,'JW Final Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'5.d0,5.d0,5.d0,5.d0 \n');
        fprintf(fid,'5.d0,5.d0,5.d0,5.d0 \n');
        fprintf(fid,'Number of Parameters to Treat with Constraints: \n');
        fprintf(fid,'4 \n');
        fprintf(fid,'Constraint Parameter List: \n');
        fprintf(fid,'1,2,3,4 \n');
        fprintf(fid,'Constraint Weights <converges to exact solution as weight --> inf>: \n');
        fprintf(fid,'1.d-14,1.d-14,1.d-14,1.d-14 \n');
        fprintf(fid,'Constraint Minimums: \n');
        fprintf(fid,'200.d0, 0.d0, 1000.d0, 0.d0, -25 -25 0.001 0.d0 \n');
        fprintf(fid,'Constraint Maximums: \n');
        fprintf(fid,'5.d5, 5.d5, 5.d6, 5.d6, -5.d0, -5.d0, 0.8 0.8 \n');
        fprintf(fid,'CG Residual Scaling Initial Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'0.04d0,0.04d0,0.04d0,0.04d0 \n');
        fprintf(fid,'0.04d0,0.04d0,0.04d0,0.04d0 \n');
        fprintf(fid,'CG Residual Scaling Final Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'0.01d0,0.01d0,0.01d0,0.01d0 \n');
        fprintf(fid,'0.01d0,0.01d0,0.01d0,0.01d0 \n');
        fprintf(fid,'Van Houten Regularization Level: \n');
        fprintf(fid,'1.2d0 \n');
        fprintf(fid,'Number of parameters to treat with soft prior: \n');
        fprintf(fid,'4 \n');
        fprintf(fid,'SP Parameter List: \n');
        fprintf(fid,'1,2,3,4 \n');
        fprintf(fid,'SP Initial Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'1.d-9,1.d-9,1.d-9,1.d-9 \n');
        fprintf(fid,'1.d-9,1.d-9,1.d-9,1.d-9 \n');
        fprintf(fid,'SP Final Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'1.d-9,1.d-9,1.d-9,1.d-9 \n');
        fprintf(fid,'1.d-9,1.d-9,1.d-9,1.d-9 \n');
        fprintf(fid,'SP start iteration delay (first N iterations do not use soft prior \n');
        fprintf(fid,'0 \n');
        fclose(fid);


            % Build MRE-submit file
    viscsubnamev9='McIlvain-Submitv9_poroSP';
    runfile_dir = ['/insomnia001/depts/mcilvain/users/mcilvain/', SubjectName, '/hex/', SubjectName, '_voxelmesh'];
    fid=fopen([inpath viscsubnamev9],'w');
    %mvfiles(length(mvfiles)+1).name=viscsubnamev7p3_noSP;
    fprintf(fid,'#!/bin/bash -l \n');
    fprintf(fid,'#SBATCH --account=mcilvain \n');
    fprintf(fid,'#SBATCH --job-name=mre_processing \n');
    fprintf(fid,'#SBATCH --time=10:00:00 \n');
    fprintf(fid,'#SBATCH --ntasks=30 \n');
    fprintf(fid,'#SBATCH --cpus-per-task=1 \n');
    fprintf(fid,'#SBATCH --mem=60G \n');
    fprintf(fid,'#SBATCH --partition=standard \n');

    fprintf(fid,'SIF_PATH="/insomnia001/depts/mcilvain/projects/NLI/mre-neuro-processing-final.sif" \n');
    fprintf(fid, 'RUNFILE_DIR="%s" \n', runfile_dir);
    fprintf(fid,'RUNFILE="runfile-v9_poroSP.dat" \n');
    fprintf(fid, 'cd "$RUNFILE_DIR" \n');
    fprintf(fid, 'apptainer exec --bind "$RUNFILE_DIR":/mnt "$SIF_PATH" bash -c ');
    fprintf(fid, '''export I_MPI_FABRICS=shm:ofi && /opt/intel/oneapi/mpi/bin/mpiexec.hydra -n 30 /MREv9p37a/MRE-Zone.discov /mnt/''"$RUNFILE"\n');
    fprintf(fid,'date \n');
    fprintf(fid,'## auto post processing \n');
    fprintf(fid,'srchtag=*RE..*0001*prop.01.mtr\n');
    fprintf(fid,'outstm=$(sed ''21!d'' runfile-v9_visc_incomp)\n');
    fprintf(fid, 'cd inv \n');
    fprintf(fid,'/insomnia001/depts/mcilvain/projects/Code/MREpostprocess/MREpostprocessv8.x $srchtag');fprintf(fid,'\n');
    fprintf(fid,'exit 0  \n');
    fclose(fid);

        % Tetvisc mesh files
        %% MREv9 runfile
        % Tetrahedral viscoealstic run file - Yes soft Prior
        tetviscoutputfv9_SP=[outstm  '_G' sprintf('%0.0f',muest) '.v9.inv.tet.visc_SP1en9_SF0p0015_CG2p2'];
        tetviscrfilev9_SP='runfile-v9_tetviscSP.dat';
        fid=fopen([inpath tetviscrfilev9_SP],'w');
        fprintf(fid,'Subzone Reconstruction Data File \n');
        fprintf(fid,'Problem Type <0=Forward Problem Only> <1+=Inverse Problem> \n');
        fprintf(fid,'1 \n');
        fprintf(fid,'Node File: \n');
        fprintf(fid,'%c',nodhmgf);fprintf(fid,'\n');
        fprintf(fid,'Element File: \n');
        fprintf(fid,'%c',elmhmgf);fprintf(fid,'\n');
        fprintf(fid,'Boundary Node File: \n');
        fprintf(fid,'%c',bcoutf);fprintf(fid,'\n');
        fprintf(fid,'Pressure BC file: \n');
        fprintf(fid,'UNUSED');fprintf(fid,'\n');
        fprintf(fid,'Region Stack File: \n');
        fprintf(fid,'%c',regoutf);fprintf(fid,'\n');
        fprintf(fid,'Measured Displacement File: \n');
        fprintf(fid,'1 \n');
        fprintf(fid,'%10.4fd0',freqHz);fprintf(fid,'\n');
        fprintf(fid,'%c',dspoutf);fprintf(fid,'\n');
        fprintf(fid,'Initial Solution File: \n');
        fprintf(fid,'0 \n');
        fprintf(fid,'Output File Stem: \n');
        fprintf(fid,'%c',outpath);fprintf(fid,'%c',tetviscoutputfv9_SP);fprintf(fid,'\n');
        fprintf(fid,'Print Detailed Runtime Debugging and Execution Comments <verb> <file>:\n');
        fprintf(fid,'.false.,.false. \n');
        fprintf(fid,'Material Model <1=isotropic> <2=orthotropic> <3=iso compress> <4=poro>: \n');
        fprintf(fid,'3 \n');
        fprintf(fid,'Number of Material Properties: \n');
        fprintf(fid,'3 \n');
        fprintf(fid,'Material Description Style <1=nodal> <2=element> [<shear modulus> <density> <Lambda modulus>]: \n');
        fprintf(fid,'1,1,1 \n');
        fprintf(fid,'Number of Parameters per Material Point: \n');
        fprintf(fid,'1,1,1 \n');
        fprintf(fid,'Property Scalars: \n');
        fprintf(fid,'%5.0f.d0,%5.0f.d0,%5.0f.d0,%8.5fd0,%10.0f.d0,%8.5fd0',[muest 2*DR*muest rhoest -1d-1 2*muest*vcomp/(3*(1-2*vcomp)) 0.0001]);fprintf(fid,'\n');
        fprintf(fid,'Zone displacement boundary condition option: 1=measured data, 2=seperate file (needs disp files on the following lines),3=calculated displacements \n');
    fprintf(fid,'1 \n');
        fprintf(fid,'Multifrequency Indicator \n');
        fprintf(fid,'.false.,.false.,.false. \n');
        fprintf(fid,'Multifrequency Alpha \n');
        fprintf(fid,'0.d0,0.d0,0.d0 \n');
        fprintf(fid,'0.d0,0.d0,0.d0 \n');
        fprintf(fid,'Number of Material Property Mesh Resolutions: \n');
    fprintf(fid,'2 \n');
    fprintf(fid,'Number of material mesh structures \n');
    fprintf(fid,'3 \n');
    fprintf(fid,'Material mesh iteration stucture (one less than number of structures)  \n');
    fprintf(fid,'3,6 \n');
    fprintf(fid,'Material Property Mesh Resolutions (x,y,z): \n');
    fprintf(fid,'%9.7f , %9.7f , %9.7f \n',vox);
    fprintf(fid,'%9.7f , %9.7f , %9.7f \n',10.*vox);
    fprintf(fid,'Material Mesh Index (1st line real part, 2nd line imag) \n ');
    fprintf(fid,'1 2 1 \n');
    fprintf(fid,'1 2 1 \n');
    fprintf(fid,'Material Mesh Index (1st line real part, 2nd line imag) \n ');
    fprintf(fid,'1 2 1 \n');
    fprintf(fid,'1 2 1 \n');
    fprintf(fid,'Material Mesh Index (1st line real part, 2nd line imag) \n ');
    fprintf(fid,'1 2 1 \n');
    fprintf(fid,'1 2 1 \n');
        fprintf(fid,'Reconstruction Indicators: \n');
        fprintf(fid,'.true.,.true. \n');
        fprintf(fid,'.false.,.false. \n');
        fprintf(fid,'.true.,.false. \n');
        fprintf(fid,'Property Estimate Variance Calculation: \n');
        fprintf(fid,'.false. \n');
        fprintf(fid,'Global forward solve to check displacement error \n');
        fprintf(fid,'.false. \n');
        fprintf(fid,'Zone Sizes (not including overlap factor, actual size = (1+2*ovlp)*siz) [x y z]: \n');
        fprintf(fid,'%12.5e,%12.5e,%12.5e',znedgelength);fprintf(fid,'\n');
        fprintf(fid,'Zone Overlap Percentage [x y z]: \n');
        fprintf(fid,'%4.3fd0,%4.3fd0,%4.3fd0',znovlp);fprintf(fid,'\n');
        fprintf(fid,'Iteration Limits [global zone]: \n');
        fprintf(fid,'100,1 \n');
        fprintf(fid,'Minimum Parameter Update Size [global zone line]: \n');
        fprintf(fid,'%c','0.1d0, 0.1d0, 0.1d0');fprintf(fid,'\n');
        fprintf(fid,'Number of Zone Iteration Structures: \n');
        fprintf(fid,'3 \n');
        fprintf(fid,'Iteration Limits for Zone Iteration Structures (NOTE:  provide one less limit than # of structures!!!): \n');
        fprintf(fid,'10,150 \n');
        fprintf(fid,'Zone Iteration Structures [<# of CG iters> <# of GN iters> <!!! QN CURRENTLY UNAVAILABLE !!!> <# of line search iters>]: \n');
        fprintf(fid,'1,0,0,1 \n');
        fprintf(fid,'2,0,0,2 \n');
        fprintf(fid,'3,0,0,2 \n');
        fprintf(fid,'Number of Processors per MUMPS Communicator \n');
        fprintf(fid,'1 \n');
        fprintf(fid,'Maximum Amount of RAM per Processor [MB] \n');
        fprintf(fid,'999999999 \n');
        fprintf(fid,'ooooooooooo  REGULARIZATION DESCRIPTORS  ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo \n');
        fprintf(fid,'Regularization Indicators [<TV> <SF> <TK> <MQ> <JW> <constraints> <CG residual> <VH> <McG> <soft prior>]: \n');
        fprintf(fid,'.false.,.true.,.false.,.false.,.false.,.false.,.true.,.true.,.true.,.true. \n');
        fprintf(fid,'Number of constant regularization iterations (final N iterations use final regularization weights) \n');
        fprintf(fid,'30 \n');
        fprintf(fid,'Number of Parameters to Treat with Total Variation: \n');
        fprintf(fid,'3 \n');
        fprintf(fid,'TV Parameter List: \n');
        fprintf(fid,'1,2,3 \n');
        fprintf(fid,'TV Delta Values: <1st line real, 2nd line imag> \n');
        fprintf(fid,'1.d-19,1.d-19,1.d-19 \n');
        fprintf(fid,'1.d-19,1.d-19,1.d-19 \n');
        fprintf(fid,'TV Initial Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'5.d-16,5.d-16,5.d-16 \n');
        fprintf(fid,'5.d-16,5.d-16,5.d-16 \n');
        fprintf(fid,'TV Final Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'5.d-16,5.d-16,5.d-16 \n');
        fprintf(fid,'5.d-16,5.d-16,5.d-16 \n');
        fprintf(fid,'Number of Parameters to Treat with Spatial Filtering: \n');
        fprintf(fid,'3 \n');
        fprintf(fid,'SF Parameter List: \n');
        fprintf(fid,'1,2,3 \n');
        fprintf(fid,'SF Gaussian filter initial Widths: <1st line real, 2nd line imag> \n');
        fprintf(fid,'0.003d0,0.003d0,0.003d0 \n');
        fprintf(fid,'0.003d0,0.003d0,0.003d0 \n');
        fprintf(fid,'SF Final Gaussian width: <1st line real, 2nd line imag> \n');
        fprintf(fid,'0.0015d0,0.0015d0,0.0015d0 \n');
        fprintf(fid,'0.0015d0,0.0015d0,0.0015d0 \n');
        fprintf(fid,'Number of Parameters to Treat with Tikhonov Regularization: \n');
        fprintf(fid,'3 \n');
        fprintf(fid,'TK Parameter List: \n');
        fprintf(fid,'1,2,3 \n');
        fprintf(fid,'TK Initial Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'1.d-18,1.d-18,1.d-18 \n');
        fprintf(fid,'1.d-18,1.d-18,1.d-18 \n');
        fprintf(fid,'TK Final Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'1.d-18,1.d-18,1.d-18 \n');
        fprintf(fid,'1.d-18,1.d-18,1.d-18 \n');
        fprintf(fid,'Number of Parameters to Treat with Marquardt Regularization: \n');
        fprintf(fid,'3 \n');
        fprintf(fid,'Distance of alpha from 1 at which MQ weights are adjusted: \n');
        fprintf(fid,'0.25d0 \n');
        fprintf(fid,'MQ Parameter List: \n');
        fprintf(fid,'1,2,3 \n');
        fprintf(fid,'MQ Weight Delta: <1st line real, 2nd line imag> \n');
        fprintf(fid,'0.5d0,0.5d0,0.5d0 \n');
        fprintf(fid,'0.5d0,0.5d0,0.5d0 \n');
        fprintf(fid,'MQ Initial Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'1.d2,1.d2,1.d2 \n');
        fprintf(fid,'1.d2,1.d2,1.d2 \n');
        fprintf(fid,'MQ Minimum Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
        fprintf(fid,'1.d-11,1.d-11,1.d-11 \n');
        fprintf(fid,'Number of Parameters to Treat with Joachimowicz Regularization: \n');
        fprintf(fid,'3 \n');
        fprintf(fid,'JW Parameter List: \n');
        fprintf(fid,'1,2,3 \n');
        fprintf(fid,'JW Initial Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'5.d0,5.d0,5.d0 \n');
        fprintf(fid,'5.d0,5.d0,5.d0 \n');
        fprintf(fid,'JW Final Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'5.d0,5.d0,5.d0 \n');
        fprintf(fid,'5.d0,5.d0,5.d0 \n');
        fprintf(fid,'Number of Parameters to Treat with Constraints: \n');
        fprintf(fid,'3 \n');
        fprintf(fid,'Constraint Parameter List: \n');
        fprintf(fid,'1,2,3 \n');
        fprintf(fid,'Constraint Weights <converges to exact solution as weight --> inf>: \n');
        fprintf(fid,'1.d-14,1.d-14,1.d-14 \n');
        fprintf(fid,'Constraint Minimums: \n');
        fprintf(fid,'200.d0, 1.d0, 1000.d0, -5.d4, 1000.d0, 0.d0 \n');
        fprintf(fid,'Constraint Maximums: \n');
        fprintf(fid,'5.d5, 5.d5, 1000.d0, -1.d-2, 1.d12, 0.d0 \n');
        fprintf(fid,'CG Residual Scaling Initial Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'0.04d0,0.04d0,0.04d0 \n');
        fprintf(fid,'0.04d0,0.04d0,0.04d0 \n');
        fprintf(fid,'CG Residual Scaling Final Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'0.01d0,0.01d0,0.01d0 \n');
        fprintf(fid,'0.01d0,0.01d0,0.01d0 \n');
        fprintf(fid,'Van Houten Regularization Level: \n');
        fprintf(fid,'1.2d0 \n');
        fprintf(fid,'Number of parameters to treat with soft prior: \n');
        fprintf(fid,'3 \n');
        fprintf(fid,'SP Parameter List: \n');
        fprintf(fid,'1,2,3 \n');
        fprintf(fid,'SP Initial Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'1.d-9,1.d-9,1.d-9 \n');
        fprintf(fid,'1.d-9,1.d-9,1.d-9 \n');
        fprintf(fid,'SP Final Weights: <1st line real, 2nd line imag> \n');
        fprintf(fid,'1.d-9,1.d-9,1.d-9 \n');
        fprintf(fid,'1.d-9,1.d-9,1.d-9 \n');
        fprintf(fid,'SP start iteration delay (first N iterations do not use soft prior \n');
        fprintf(fid,'0 \n');
        fclose(fid);

      
       % Build MRE-submit file
    viscsubnamev9='McIlvain-Submitv9_tetviscSP';
    runfile_dir = ['/insomnia001/depts/mcilvain/users/mcilvain/', SubjectName, '/hex/', SubjectName, '_voxelmesh'];
    fid=fopen([inpath viscsubnamev9],'w');
    %mvfiles(length(mvfiles)+1).name=viscsubnamev7p3_noSP;
    fprintf(fid,'#!/bin/bash -l \n');
    fprintf(fid,'#SBATCH --account=mcilvain \n');
    fprintf(fid,'#SBATCH --job-name=mre_processing \n');
    fprintf(fid,'#SBATCH --time=10:00:00 \n');
    fprintf(fid,'#SBATCH --ntasks=30 \n');
    fprintf(fid,'#SBATCH --cpus-per-task=1 \n');
    fprintf(fid,'#SBATCH --mem=60G \n');
    fprintf(fid,'#SBATCH --partition=standard \n');

    fprintf(fid,'SIF_PATH="/insomnia001/depts/mcilvain/projects/NLI/mre-neuro-processing-final.sif" \n');
    fprintf(fid, 'RUNFILE_DIR="%s" \n', runfile_dir);
    fprintf(fid,'RUNFILE="runfile-v9_tetviscSP.dat" \n');
    fprintf(fid, 'cd "$RUNFILE_DIR" \n');
    fprintf(fid, 'apptainer exec --bind "$RUNFILE_DIR":/mnt "$SIF_PATH" bash -c ');
    fprintf(fid, '''export I_MPI_FABRICS=shm:ofi && /opt/intel/oneapi/mpi/bin/mpiexec.hydra -n 30 /MREv9p37a/MRE-Zone.discov /mnt/''"$RUNFILE"\n');
    fprintf(fid,'date \n');
    fprintf(fid,'## auto post processing \n');
    fprintf(fid,'srchtag=*RE..*0001*prop.01.mtr\n');
    fprintf(fid,'outstm=$(sed ''21!d'' runfile-v9_visc_incomp)\n');
    fprintf(fid, 'cd inv \n');
    fprintf(fid,'/insomnia001/depts/mcilvain/projects/Code/MREpostprocess/MREpostprocessv8.x $srchtag');fprintf(fid,'\n');
    fprintf(fid,'exit 0  \n');
    fclose(fid);

    end


end

